### ISSUE TITLE
User saml config options NOT found

### ISSUE THREAD

**Issue by sjash** [nextcloud/user_saml#105]
![user_saml-err](https://cloud.githubusercontent.com/assets/15723972/24101142/22a56486-0d9d-11e7-86d9-ab80d15415ae.png)

Unable to get config options for user_saml app.I have configured LDAP as backend and its working
Nextcloud version- 11.0.1
PHP - 7.0
Mysql -5.6

Kindly help!

**Comment by LukasReschke** [comment]
Closing due to missing feedback.
