### ISSUE TITLE
Can't configure SSO authentication

### ISSUE THREAD

**Issue by Miceldars** [nextcloud/user_saml#109]
Hello.

Using a fresh install of nextcloud 11.0.2, I tried to use user_saml to configure SSO authentication.
But when I click on "Use environment variable" in Admin --> SSO & SAML authentication, it just reload the exact same page. Same thing with "Use built-in SAML authentication", it shows the same page, nothing more. There is no form to configure SAML authentication or use environment variable.

There is nothing in the nextcloud.log

Server : centos 7
Nextcloud version : 11.0.2 (same problem with 11.0.0 and 11.0.1)

**Comment by mokas01** [comment]
i have the same issue

Server : armbian jessie 8.8
nextcloud version : 11.0.2

**Comment by jh23453** [comment]
I had the same problem - I got it working with the following additions:
```
mysql> select * from oc_appconfig where appid='user_saml';
+-----------+-------------------------------------+----------------------+
| appid     | configkey                           | configvalue          |
+-----------+-------------------------------------+----------------------+
| user_saml | enabled                             | yes                  |
| user_saml | general-require_provisioned_account | 1                    |
| user_saml | general-uid_mapping                 | REMOTE_USER          |
| user_saml | installed_version                   | 1.3.2                |
| user_saml | type                                | environment-variable |
| user_saml | types                               | authentication       |
+-----------+-------------------------------------+----------------------+
```
After that I could also change to config in the WebUI. There seems to be a problem
with the app-installation.

There's another catch, you need to change the location from /nextcloud/index.php/login to:
```
<Location /nextcloud/index.php/apps/user_saml/saml/login>
    SSLRequireSSL
    AuthType Kerberos
...
```
I'm not sure if I find time to try a clean installation to see where it fails (I started with 12beta).

**Comment by marcelin** [comment]
Hi everyone!!!

I've tried all ur configuration but SSO does't work. I'm using Nextcloud with "LDAP user and group backend" and "SSO & SAML authentication" enabled. i'm using windows server 2012 as LDAP auth service. My web sever is apache2

Please I need Help.

**Comment by kundansingh27feb** [comment]
Can anyone help me to resolve the IDP issue in nextcloud. I am getting the below screen:

![error](https://user-images.githubusercontent.com/27075173/34552522-f6a9539e-f147-11e7-8033-074c4baba57a.png)
