### ISSUE TITLE
Transition from user_ldap to user_saml problem

### ISSUE THREAD

**Issue by Emi94** [nextcloud/user_saml#117]
I have a nextcloud 12.0.0 server that authenticates users from LDAP using the user_ldap app. I enabled user_saml and using an environment variable made it authenticate users using a CAS server (which uses the same LDAP server). Now when i login with a user, nextcloud doesn't recognize the user as the same one i was using before.
![screenshot from 2017-05-29 16 35 43](https://cloud.githubusercontent.com/assets/11816318/26551824/1de1c36e-448d-11e7-8dbd-ac9ef35e3879.png)
These two users are actually the same, the first from user_ldap and second from user_saml. 

As an environment variable i used HTTP_CAS_USER and this is how i configured mod_auth_cas:
```
        CASVersion 2
        CASLoginURL https://192.168.0.206:8443/cas/login
        CASValidateURL https://192.168.0.206:8443/cas/serviceValidate
	CASValidateServer Off

        <Location "/index.php/login">
                AuthType CAS
                AuthName "CAS Authentication"
                require valid-user
        </Location>


        <Location "/index.php/apps/user_saml/saml/login">
                AuthType CAS
                AuthName "CAS Authentication"
                require valid-user
        </Location>
```

Any idea how to make nextcloud see them as the same user?

**Comment by jh23453** [comment]
Look into you LDAP tree which attribute contains the right value. For me it was uid.
Enter that attribute in the AD/LDAP configuration, expert tab as attribut for internal username.
Be aware that this invalidate user settings...

**Comment by Emi94** [comment]
Yes i discovered this myself, but if i set internal username in AD/LDAP configuration i have to remap the users which leads to "new users" without the already uploaded files and other settings

**Comment by LukasReschke** [comment]
There's not much we can do here. The UID needs to match the one in the LDAP backend, if that isn't the case you end up with issues as such. Sorry :(
