### ISSUE TITLE
Allow to disable the auto-provisioning

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/user_saml#12]
* only do the authentication via SAML and get the user info from a separately set up LDAP, that uses the same usernames

**Comment by MorrisJobke** [comment]
That would allow to share to a user that never logged in ;)

**Comment by LukasReschke** [comment]
I'd just implement it the way that if LDAP is enabled it will always check if the user is available there as well. Seems like the easiest approach without config nightmare. Any objections on that?

**Comment by LukasReschke** [comment]
Or do we actually really need another checkbox that says:

> - Disables auto-provisioning. Only authenticate user if found in another enabled backend

?

**Comment by MorrisJobke** [comment]
> Or do we actually really need another checkbox that says:

I think so. This makes the software more robust against user backend outages ;)

**Comment by flotpg** [comment]
I have this issue, not sure if related to this.
- using Azure AD as SAML, user prinicpal name is mapped as UID in nextcloud
  - user logs in via SAML with user@domainc.com (same UPN exists in local AD/LDAP)
  - if ldap is also enabled, i can see the user when he's never been signed in under users in nextcloud, so nextcloud <> ldap is working
  - when enabling SAML with "user has to exist in some other backend like LDAP" option the user is not able to sign in > ERROR: not provisioned
- when i disable SAML temporarily, login the user the first time via LDAP (i guess its then provisioned) and then enable SAML again, the user is able to login via SAML

Wouldn't it be great if the user would be able to sign in via SAML, if= exists in LDAP > provision user > login via SAML?
