### ISSUE TITLE
NextCloud 12 - SSO & SAML authentication - app can’t be activate

### ISSUE THREAD

**Issue by AlexSam8** [nextcloud/user_saml#121]
### Steps to reproduce
1. Install NextCloud 12 on CentOS 7 + Apache 2.4.6 + PHP 7.1 + PostgreSQL 9.4  
2. Download SSO & SAML authentication app from https://apps.nextcloud.com/apps/user_saml
3. Go to apps panel and try to activate (for me the activate button is fade out and can't activate app. The remove buton works perfect)

### Expected behaviour
Tell us what should happen

**Activate the app**

### Actual behaviour
Tell us what happens instead

![image](https://user-images.githubusercontent.com/29724023/27576232-f6578d8e-5b24-11e7-80e9-04ea612d4339.png)

**The activate button is fade out. can't click on it.** 

### Server configuration

**Operating system**:
CentOS 7
**Web server:**
Apache 2.4.6
**Database:**
Postgres 9.4
**PHP version:**
php 7.1
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12
**Where did you install Nextcloud from:**
**https://download.nextcloud.com/server/releases/nextcloud-12.0.0.zip**

**List of activated apps:**
**Dezactivated all apps - same problem**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

[root@prod nextcloud]# sudo  -u apache php occ app:list
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - announcementcenter: 3.1.0
  - calendar: 1.5.3
  - circles: 0.11.0
  - comments: 1.2.0
  - dav: 1.3.0
  - deck: 0.2.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external_sia: 0.1.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.1.2
  - ownbackup: 17.5.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - files_external
  - user_external
  - user_saml

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder


[root@prod nextcloud]# sudo -u apache php occ config:list system
{
    "system": {
        "instanceid": "ocp41r9hlxm9",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.254.11.56"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/10.254.11.56\/nextcloud",
        "dbtype": "pgsql",
        "version": "12.0.0.29",
        "dbname": "nextcloud12",
        "dbhost": "10.254.11.168",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}



or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**
Chrome 48

**Operating system:**
Windows 7

#### Nextcloud log (data/owncloud.log)
```
{"reqId":"WVH5PAaTx5n301exv4ihcwAAAAA","level":3,"time":"2017-06-27T06:20:44+00:00","remoteAddr":"10.250.100.219","user":"admin","app":"appstoreFetcher","method":"GET","url":"\/nextcloud\/index.php\/settings\/apps\/list?category=installed","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ConnectException\",\"Message\":\"cURL error 6: Could not resolve host: apps.nextcloud.com; Name or service not known\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(103): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\ConnectException))\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(138): GuzzleHttp\\\\Client->get('https:\\\/\\\/apps.ne...', Array)\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/App\\\/AppStore\\\/Fetcher\\\/Fetcher.php(99): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/apps.ne...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/App\\\/AppStore\\\/Fetcher\\\/AppFetcher.php(66): OC\\\\App\\\\AppStore\\\\Fetcher\\\\Fetcher->fetch('', '')\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/App\\\/AppStore\\\/Fetcher\\\/Fetcher.php(162): OC\\\\App\\\\AppStore\\\\Fetcher\\\\AppFetcher->fetch('', '')\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Installer.php(394): OC\\\\App\\\\AppStore\\\\Fetcher\\\\Fetcher->get()\\n#13 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/AppSettingsController.php(291): OC\\\\Installer::isUpdateAvailable('circles', Object(OC\\\\App\\\\AppStore\\\\Fetcher\\\\AppFetcher))\\n#14 [internal function]: OC\\\\Settings\\\\Controller\\\\AppSettingsController->listApps('installed')\\n#15 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#16 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AppSettingsController), 'listApps')\\n#17 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AppSettingsController), 'listApps')\\n#18 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'listApps', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#19 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#20 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#21 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/settings\\\/apps\\\/...')\\n#22 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#23 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":49}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/48.0.2564.82 Safari\/537.36","version":"12.0.0.29"}



Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by herrfeuer** [comment]
Same here.

**Comment by AlexSam8** [comment]
Works SSO & SAML authentication app with NextCloud 12  - on CentOS 7 - for other person ?

**Comment by apw1388** [comment]
Hi,
we run Nextcloud 12 on CentOS 7.3. The user_saml works fine with mapping of username and email.

**Comment by AlexSam8** [comment]
I downloaded GitHub - master version of this app - but still doesn't work. 

Any sugestions please ?

**Comment by LukasReschke** [comment]
The app is not compatible with PHP 7.1 at the moment.

**Comment by poVoq** [comment]
At least activating works fine on my php7.1 system.

**Comment by AlexSam8** [comment]
Thank you @LukasReschke - PHP version is the problem. 

Now I have 2 servers: 
1. with NextCloud 12 and PHP 7.0 
  - app SSO & SAML can be activate
  - but when I enter in settings/users (to give admin rights to an user)  i recive this error (from LDAP app)

![image](https://user-images.githubusercontent.com/29724023/28268557-618bd87a-6b07-11e7-9899-4966645136e7.png)

2. with NextCloud 12 and PHP 7.1
  - I can enter in settings/users and give admin rights to the users
  - app SSO & SAML can't be activate 
      Sir @poVoq  can you help me please with some advices, can you give me the link who you used for download SSO & SAML app ? You have CentOS 7 and Apache?

Sorry for disturbing - SSO is the last piece for this lovely project!

 Thank You!

**Comment by poVoq** [comment]
Shared hosting with OVA so not sure what OS exactly. However the system runs on php7.1 and Apache according to the admin panel. But to be honest, I only know that I can activate it, have not tried configurating it yet as I am still busy setting up a working SAML idp solution.

**Comment by AlexSam8** [comment]
If i want enable app  user_saml from OCC => this error 

  [Exception]
  App "SSO & SAML authentication" cannot be installed because the following dependencies are not fulfilled: The library mcrypt is not available.

  On PHP 7.0 I installed module php70w-mcrypt-7.0.22-2.w7.x86_64 and all work fine. 

  On PHP 7.1 I installed php71w-mcrypt-7.1.8-2.w7.x86_64 ,  but after reboot the server gave me this error on first page

PHP module dom not installed.
Please ask your server administrator to install the module.
PHP module XMLReader not installed.
Please ask your server administrator to install the module.
PHP modules have been installed, but they are still listed as missing?
Please ask your server administrator to restart the web server.

I tried to install module php71w-xml-7.1.8-2.w7.x86_64 ,  but module was up to date (remove and reinstall doesn't work)

**Comment by robertoandrade** [comment]
I'm getting a different error when trying to enable this on a v13a installation:

```
PHP Fatal error:  Class OCA\\User_SAML\\UserBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\Authentication\\IApacheBackend::getLogoutAttribute) in /var/www/html/apps/user_saml/lib/UserBackend.php on line 34
```

Any clues as to why that may happen?
