### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by tal2301** [nextcloud/user_saml#122]
In my Nextcloud Enviorment I am using ADFS and for each user that logs in the username is automatically a adfs parameter however i would like it to show the users name from the AD
how can i change this setting

**Comment by Skywalker-11** [comment]
@tal2301 So is authentication for you working with ADFS? Can you describe what settings are necessary to set up basic authentication with it? Other people (including me) have problems to get it working (see #23, #104, #107)

**Comment by tal2301** [comment]
I only have ADFS authentication with no basic authentication

**Comment by Skywalker-11** [comment]
Thats what I mean. What settings are needed to get the ADFS authentication working.

**Comment by tal2301** [comment]
In the Identity Provider Data Settings i inserted my adfs server links
and also inserted the certificate of the adfs server

**Comment by LukasReschke** [comment]
Seems more like a setup issue => help.nextcloud.com
