### ISSUE TITLE
SAML provisioned Users can't login

### ISSUE THREAD

**Issue by rzmf** [nextcloud/user_saml#124]
### Steps to reproduce
1. install nextcloud12 + user_saml
2. fill in metadata, enable user_saml
3. Login to nextcloud as new user via Redirect to SAML-IDP and Redirect back to nextcloud

### Expected behaviour
User should see the files app

### Actual behaviour
{"reqId":"QajQLqx8jXCC12FfVhk5","level":3,"time":"2017-06-30T10:27:28+00:00","remoteAddr":"XXXXXXXXXXXXX","user":"XXXXXXXXX@DOMAIN","app":"index","method":"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(130): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(159): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":543}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; Trident\/7.0; rv:11.0) like Gecko","version":"12.0.0.29"}

if the user gets created first in nextcloud, everything works as expected

### Server configuration

**Operating system**:
Centos 7

**Web server:**
nginx

**Database:**
Postgresql

**PHP version:**
PHP 7

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**List of activated apps:**
  - activity: 2.5.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - user_saml: 1.3.2
  - workflowengine: 1.2.0

**Nextcloud configuration:**

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "XXXXXXXXX",
            "XXXXXXXXX:443"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "pgsql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "pgcloud.XXXXXXXXXXX",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "ocpsqm6rq61j",
        "filesystem_check_changes": "1",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "has_internet_connection": "false",
        "theme": "XXX",
        "redis": {
            "host": "localhost",
            "port": "6379",
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "loglevel": 0,
        "maintenance": false
    }
}### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)

see above

#### Browser log

not relevant

**Comment by jospoortvliet** [comment]
If you have a support contract be sure to file this in https://portal.nextcloud.com to get it fixed soon.

Did this work before? Is it on a fresh installation or upgraded?

**Comment by rzmf** [comment]
worked fine on 11.

this is a fresh install

**Comment by herrfeuer** [comment]
@jospoortvliet i am waiting for this to be fixed to upgrade the Nextclouds of my local hackerspace.
Your answer is odd. You mean we should pay $$$ for get a Bug in a core feature fixed - we are tight every month to pay the power for our servers.
---
fire [enemy.org servus.at dyne.org devlol.org]

**Comment by rzmf** [comment]
seems to work now, no changes made....

**Comment by jospoortvliet** [comment]
@herrfeuer well, I'm just being realistic, sorry. Work hours cost money, also the hours in an open source company. Of course it'd be great if we could offer paid support (priority bug fixing) for free, but that doesn't work. You don't get free electricity or water or housing or servers either, right?

But we certainly strive to fix any bug we encounter and if you still suffer from it you should report as much info on it as possible so we have a chance to debug it...

**Comment by herrfeuer** [comment]
@jospoortvliet i think you didnt got it. @rzmf reported a bug and i could (i still can) reproduce it. Instead of thank people for reporting Bugs and sometimes sending patches (for free) you ask for money to maybe get it fixed. I never asked for professional support i just wanted to report a bug and help to get it fixed.  
If you dont want people to report Bugs set the repo permissions right.
Please Mr. Marketing Manager, People person, technology enthusiast and all-things-open evangelist go back in your Facebook Marketing World do nice things there and dont mess up things here. 
@LukasReschke @nickvergessen

**Comment by jospoortvliet** [comment]
@herrfeuer read what I said before complaining. I never said you have to pay to get the bug fixed - only if you need it fixed SOON. Everything not paid depends on volunteer work and free time of people.

It is closed now because it works for the initial reporter. If it still doesn't work for you, add any info you have on it so it can be fixed when somebody has time to fix it...
