### ISSUE TITLE
SAML provisioned users don't see "Full Name" after login

### ISSUE THREAD

**Issue by rzmf** [nextcloud/user_saml#125]
### Steps to reproduce
1. configure user_saml with attribute mappings for displayname
2. login with saml as non-existent account
3. go to /settings/personal

### Expected behaviour
See displayname

### Actual behaviour
Displayname is UID.
odd thing is: as admin under /settings/users displayname is correct with the mapped values from SAML-Token

### Server configuration
**Operating system**:
Centos 7

**Web server:**
nginx

**Database:**
postgres
**PHP version:**
php 7.0

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - user_saml: 1.3.2
  - workflowengine: 1.2.0

**Comment by LukasReschke** [comment]
https://github.com/nextcloud/user_saml/pull/137 should probably resolve this.

**Comment by LukasReschke** [comment]
Testing appreciated 😄
