### ISSUE TITLE
Allow native Nextcloud admins to still login

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/user_saml#126]
Is it possible to login as a normal admin user to the nextcloud instance without the SSO to hit in?

Do we want to add a little flag for this like that:

https://example.org/login?admin

Which then shows the normal login prompt instead of redirecting to the SSO portal?

cc @LukasReschke

**Comment by herrfeuer** [comment]
Thnx @MorrisJobke you where faster than me opening this issue. 
Please flag this as a Bug, there is no way to login if SAML fails. I have to disable user_saml with occ to login as admin if something is wrong like a expired cert or swichting idp.

**Comment by rzmf** [comment]
+1

**Comment by MorrisJobke** [comment]
Just a little reference to the SAML docs: https://docs.nextcloud.com/server/11/admin_manual/configuration_server/sso_configuration.html#enabling-the-sso-saml-app

**Comment by apw1388** [comment]
There is an open Pull Request #98 which allows Login with SAML and local users at the same time. It doesn't use a flag but maybe it helps.

**Comment by poVoq** [comment]
According to the old documentation: ( https://github.com/nextcloud/apps/tree/master/user_saml )

> There is a parameter in the settings named force_saml_login to avoid the login form, redirecting directly to the IdP when accesing owncloud. If you are an admin and you want to log in using the login form, then use the GET param admin_login to deactivate the forced redirection.

Not working anymore?

**Comment by MorrisJobke** [comment]
> Not working anymore?

Yes, because it is the old app and the old documentation which has 0 in common with this app except the name.

**Comment by LukasReschke** [comment]
This is still an enhancement and not a bug. 😉 – Has been implemented by purpose like this.

Sure it's not the preferred behaviour of all people but hey … it is like it is. And this surely will be adjusted one time once priorities are high enough. (aka either I find enough time to do this driven by customer demand or someone creates a pull request also including integration tests)

**Comment by apw1388** [comment]
@LukasReschke Are you missing the integration tests in #98 ?

**Comment by LukasReschke** [comment]
@apw1388 Correct. This adds group mapping and alternative logins (which should be 2 PRs) and I miss automated integration tests for this covering the following cases:

1. Group already exists
2. Group does not exist
3. No groups configured
4. …

As there actually is a demand on this here this is something that will be done. But the priority on my priority list is rather low for this one. (as in probably not done in August, maybe at the start of September)

I'm rather reluctant and conservative when it comes to merging changes here as this is a quite essential app used in many enterprise deployments potentially breaking a lot of stuff. Anything that isn't entirely covered by unit and integration tests may really need it's time to get merged.

**Comment by posledov** [comment]
IMHO, the proper way for the direct login is to add two additional (sub-)options for `Allow the use of multiple user back-ends` **while it's disabled/unchecked**:
1. `Allow direct login with access-token`
2. `Direct login access-token value (minimum 16 symbols)`

Requirements/rules for `1.` and `2.`:
- `1.` is optionally and disabled/unchecked by default
- `2.` is mandatory and should be able to auto-generate of the value (`Generate` button)
- Bellow `2.` must be text-hint with URL for direct-login page (for example: `https://<your.nextcloud.domain>/login?direct=1&access-token=1234567890ABCDEF`)

For the direct-login process while `Allow the use of multiple user back-ends` is disabled and `Allow direct login with access-token` is enabled, there should be only two mandatory requirements:
- Check `access-token` and `login/password` at once. I mean always show the login page, even if the `access-token` is incorrect.
- If the `login/password` or `access-token` are wrong, never specify what exactly

**Comment by MorrisJobke** [comment]
The way to do this here for now is to go to this URL: `https://example.org/login?direct=1` - there you can see the input field while not interrupting the normal login flow for all the other users with SAML login.

I will close the ticket for now.

@posledov Your idea is also nice, but as of now this is the only request and we try to focus on other stuff. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by flotpg** [comment]
How can I disable this?

WTH? This is a big security issue - We punish users through all that MFA/TOTP hassle, route them through Azure Conditional Access Policies to make sure only trusted/domain joined/etc. devices are able to access the Nextcloud instance and now this?
The user only has to change the URL to login from any device?

**Comment by herrfeuer** [comment]
@flotpg you can catch /login?direct=1 with a rewrite rule in Apache.
It's merely a matter of time if they want money for fixing security Vulnerabilities.

**Comment by rullzer** [comment]
@flotpg they can only do direct login if they have an actual account on the system. If you only have SAML setup then the direct login is only for the admins on the system that do not have a SAML account. When you use pure SAML Nextcloud doesn't even know the password of the SAML user so it can't actually authenticate users.

Or are your using SAML in combination with LDAP?

**Comment by florian-obradovic** [comment]
@rullzer yes, we use ldap as backend.

**Comment by rullzer** [comment]
Ah ok so that is the issue.
Let me see what we can do.

**Comment by blizzz** [comment]
then you set a login filter that never satisfies

**Comment by florian-obradovic** [comment]
@blizzz can you please explain a little more detailed?

**Comment by blizzz** [comment]
> @blizzz can you please explain a little more detailed?

https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap.html#login-attributes-tab

use a filter like `thisAttributeDoesNotExist=%uid` for login.

**Comment by florian-obradovic** [comment]
@blizzz i still don't get how this helps - what do I miss ?

I'll try to explain what we do:

1. LDAP as backend
2. we already have filters like only users from these groups can login
3. SAML is Azure AD / O365 **but user must exist in backend** (to have group member ships, encryption keys, etc.)
     Otherwise we would not be able to user AD groups nextcloud because you don't get this info from SAML
4. Authentication should be possible **via SAML only**! Our SAML Authentication Front-End is AzrueAD where we have multiple checks in place (User has permission? MFA? Trusted Device? Device is compliant?, etc ;) )

**Comment by blizzz** [comment]
> @blizzz i still don't get how this helps - what do I miss ?

Then please discuss it at the [forums](https://help.nextcloud.com): I provided all the info you need.

**Comment by barta-home** [comment]
Had the same issue after update to new nextcloud version. 

For me it works again if I use following url:

```
https://<your.nextcloud.domain>/index.php/login?direct=1
```
