### ISSUE TITLE
New users are not configured

### ISSUE THREAD

**Issue by KroniK907** [nextcloud/user_saml#149]
When you create a new user, their home directory is initialized when they first log in. Unfortunately when using the user_saml app, if you create a new user in both your IdP and in next cloud, they will not be able to log in because the user has no home directory, and the user_saml app does not run this initialization. 

I'm not sure if this is an issue with the nextcloud/server or this app specifically, as I'm not really able to tell if an external app is even given the ability to initialize new users. 

Currently, every time I have a new user, I have to create a new nextcloud user, disable user_saml, log them in, then re-enable user_saml.

**Comment by shukon** [comment]
Not really reproducable with Nextcloud 18 in any way (just fyi), I can create a user in nextcloud with occ and log in using a saml with keycloak.
