### ISSUE TITLE
Password prompt if admin wants to create user in user management

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/user_saml#157]
* login via user_saml
* wait at least 30 minutes
* go to user management and try to create user
* actual: password prompt is shown
* expected: for saml users the prompt should not be shown

cc @LukasReschke 

**Support:** https://support.nextcloud.com/#ticket/zoom/1220

**Comment by rullzer** [comment]
Fixed with https://github.com/nextcloud/server/pull/7487
