### ISSUE TITLE
Unsigned SAML Response

### ISSUE THREAD

**Issue by wanneut** [nextcloud/user_saml#165]
### Description

I enabled and configured the SSO & SAML authentication for SAML authentication.

When I try to login, i get redirected to the IDP, asked for my credentials, and and redirected back to NextCloud.
But there I get the  message "Unsigned SAML Response that contains a signed and encrypted Assertion with encrypted nameId is not supported.".
That seems wrong. When I dump the SAML-Response with wireshark I can see a signed Response:
_<saml2p:Response
…<ds:Signature … </ds:Signature> …
</saml2p:Response>_

Btw. The IDP supports only encrypted nameId saml:Assertion schould be signed and encrypted. 
So all "Signatures and encryption" check boxes are selected. (But I tried serval other configurations.)

Log says also:
_invalid_response
Unsigned SAML Response that contains a signed and encrypted Assertion with encrypted nameId is not supported._

i'm not really sure if it is a bug or if I just making something wrong. But it seems to me that at least the error-Message is wrong.
I also don't know how I can further debug this problem.

### Expected behaviour
Login

### Actual behaviour
Getting the error message:
Unsigned SAML Response that contains a signed and encrypted Assertion with encrypted nameId is not supported.

### Server configuration

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.31

**PHP version:** 7.0.22-0ubuntu0.16.04.1

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated Version?** fresh install

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Comment by solracsf** [comment]
Try latest version of plugin and report back in a new issue if needed.
