### ISSUE TITLE
mcrypt not available anymore for PHP 7.2 

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/user_saml#168]
It is listed as required dependency. We should look into this and if it is possible to drop it.

https://liorkaplan.wordpress.com/2017/09/10/php-7-2-is-coming-mcrypt-extension-isnt/

cc @schiessle

**Comment by normanu** [comment]
Archlinux no longer has mcrypt for php 7.2

**Comment by rullzer** [comment]
So it seems this is required by the php-saml lib we use. So we should for now limit this app to php 7.0 and php 7.1 (for NC14)

The 3.0.0.x-dev (see https://packagist.org/packages/onelogin/php-saml#3.0.0.x-dev) doesn't require it anymore.

**Comment by jwstolk** [comment]
I'm also running into this dependency.
It looks like Ubuntu server 18.04 (beta) no longer has PHP 7.1, only PHP 7.2
Could I install Nextcloud without php-saml?

**Comment by vahem2lu** [comment]
Looking a possibility too to use SAML plugin with Nextcloud 12 and PHP7.2.

**Comment by jkolo** [comment]
Install pecl-mcrypt for Ubuntu: https://serverpilot.io/community/articles/how-to-install-the-php-mcrypt-extension.html
For Gentoo I wrote ebuild: https://git.kolosowscy.pl/jurek/gentoo-overlay/blob/master/dev-php/pecl-mcrypt/pecl-mcrypt-1.0.1.ebuild

**Comment by GrimKriegor** [comment]
[The official Docker image also dropped mcrypt recently.](https://github.com/nextcloud/docker/pull/416#issuecomment-411162239)

Should 'user_saml' be removed at least from the 'Enterprise bundle' until this gets sorted out?

**Comment by ChessSpider** [comment]
Yeah woke up this morning to a broken nextcloud-docker after updating👎 . Hope this can get fixed soon.

**Comment by cloud-rocket** [comment]
++ Upgraded the system and figured out SSO is not working

**Comment by schiessle** [comment]
Sadly, php_saml, the 3rd party lib we are using didn't released a version without the mcrypt dependency yet. But they already removed it on their development branch and I already ported our app to the dev branch in order to test it: https://github.com/nextcloud/user_saml/pull/236

I did some tests and everything seems to work. But I probably didn't tested all different config combinations. So in case you want to give it a try, feel free to take the code from the PR mentioned above and report back if everything doesn't work as expected. This helps us to iron out all possible issues early so that we can do a release as soon as a stable version of php_saml without mcrypt is available.

**Comment by svoop** [comment]
FYI: No `mcrypt` for PHP 7.2 on Gentoo, too. While a `pecl-mcrypt` ebuild could fill the gap, nobody has given it a shot yet – and quite likely nobody ever will.

**Comment by jkolo** [comment]
> FYI: No `mcrypt` for PHP 7.2 on Gentoo, too. While a `pecl-mcrypt` ebuild could fill the gap, nobody has given it a shot yet – and quite likely nobody ever will.

https://git.kolosowscy.pl/jurek/gentoo-overlay/tree/master/dev-php/pecl-mcrypt

**Comment by nachoparker** [comment]
I got it working on Raspbian Stretch by using `pecl`

```
    apt install  gcc make autoconf libc-dev pkg-config php-pear php7.2-dev libmcrypt-dev
    wget https://raw.githubusercontent.com/pear/Archive_Tar/1.4.3/Archive/Tar.php -O /usr/share/php/Archive/Tar.php     # https://github.com/oerdnj/deb.sury.org/issues/668 #<- pecl doesn't work in php7.2
    echo -e "\n" | pecl install mcrypt-1.0.1
    echo "extension=mcrypt.so" > /etc/php/${PHPVER}/mods-available/mcrypt.ini
    phpenmod mcrypt
```

**Comment by pasikarkkainen** [comment]
upstream php-saml v3.0.0 has been released. it should now work with PHP 7.2 / without mcrypt.

**Comment by schiessle** [comment]
great, I will update this pull request with the final https://github.com/nextcloud/user_saml/pull/236

**Comment by schiessle** [comment]
Pull request is updated, everyone is invited to test/review it

**Comment by schiessle** [comment]
it is merged... release will follow soon

**Comment by cloud-rocket** [comment]
@MorrisJobke, it more or less mean that Docker users will not be able to fix SSO until December when v15 will be out? Tnx

**Comment by MorrisJobke** [comment]
> @MorrisJobke, it more or less means that Docker users will not be able to fix the SSO until December when v15 will be out? Tnx

user_saml is independent from the server release and works on all Nextcloud versions since 12.

**Comment by cloud-rocket** [comment]
So when is the minor release planned? tnx

**Comment by MorrisJobke** [comment]
November 22: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by evaryont** [comment]
Will there be a new release of user_saml before then?

**Comment by MorrisJobke** [comment]
cc @schiessle @rullzer

**Comment by luisfavila** [comment]
It's a joke we have to wait months for something that's already been fixed

**Comment by mvitale1989** [comment]
Confirming that user_saml v2.0.0 installs and works like a charm, even in docker. Thank you!!
