### ISSUE TITLE
Settings look a bit crowded

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/user_saml#17]
* maybe the settings should get a bit more line-spacing to not look that crowded

See #16 - maybe someone from the @nextcloud/designers want to check this out :)

![bildschirmfoto 2016-06-30 um 16 39 07](https://cloud.githubusercontent.com/assets/245432/16492331/b3ef2e62-3ee1-11e6-8441-28c573f50b6c.png)

Optional settings could be expanded by clicking on the text:

![bildschirmfoto 2016-06-30 um 16 39 49](https://cloud.githubusercontent.com/assets/245432/16492359/ca2d4970-3ee1-11e6-8a86-ddb106e6331f.png)
![bildschirmfoto 2016-06-30 um 16 39 52](https://cloud.githubusercontent.com/assets/245432/16492361/ca2e6d5a-3ee1-11e6-974d-a5348bb523ed.png)
![bildschirmfoto 2016-06-30 um 16 40 01](https://cloud.githubusercontent.com/assets/245432/16492360/ca2dd782-3ee1-11e6-8935-819930ebd3ff.png)

**Comment by jancborchardt** [comment]
This will definitely be easier once we separate the long settings page into multiple pages. Then we can promote the subheadings to h2, which will improve the style a lot.

So … @MorrisJobke are you down to work on the separation of the admin settings page? In one go we could then also combine it with the personal settings to just be »Settings«. In the left navigation, the Personal settings would come first.

**Comment by MorrisJobke** [comment]
> This will definitely be easier once we separate the long settings page into multiple pages. Then we can promote the subheadings to h2, which will improve the style a lot.

https://github.com/nextcloud/server/issues/267


I could check this out, sure. I will close this here then ;)
