### ISSUE TITLE
New users got no default (skeleton) documents

### ISSUE THREAD

**Issue by apw1388** [nextcloud/user_saml#172]
We enabled the user_saml module to authenticate new users with our IdP. New users have an empty home folder within unity and the default/skeleton documents like Nextcloud manual are not stored in their homes. If we create a new local user, those documents are present. This issue happened to all users, with user_saml login, across different browsers and OS.

I don't know if this is a problem of user_saml module or Nextcloud server, but it appears if new users login by user_saml module.

### Steps to reproduce
1. Install Nextcloud 12.0.4
2. Enable user_saml module
3. Sign in with SAML IdP as a new user

### Expected behaviour
The sync clients pop up for new user is shown and default (skeleton) documents are stored in home folder. ~ 7MB of user space are used by this documents.

### Actual behaviour
The pop up is shown and no files are stored/shown in the home folder.  No space is used.

### Server configuration
**Operating system**:
CentOS 7.3
**Web server:**
Apache
**Database:**
MariaDB  5.5.52
**PHP version:**
7.0.25
**Nextcloud version:** (see Nextcloud admin page)
12.0.4
**Where did you install Nextcloud from:**
tar.bz2 file from Nextcloud homepage

**List of activated apps:**
  - activity: 2.5.2
  - b2sharebridge: 0.2.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - user_saml: 1.4.0
  - workflowengine: 1.2.0

**Nextcloud configuration:**
<?php
$CONFIG = array (
  'instanceid' => 'oc55b618ba84',
  'version' => '12.0.4.3',
  'dbtype' => 'mysql',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'updatechecker' => false,
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto, auto, auto, auto, auto, auto',
  'memcache.local' => '\OC\Memcache\APCu',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 10,
  'htaccess.RewriteBase' => '/',
  'maintenance' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
);

### Client configuration
**Browser:**
Firefox, Chromium, Chrome

**Operating system:**
Arch Linux, Ubuntu, Windows
### Logs
nothing in log files

**Comment by soudis** [comment]
same here, clues anyone? or ist this the normal behaviour?

**Comment by Ryonez** [comment]
Issue is still present.

**Comment by FGIKCM** [comment]
yeah the PR was not accepted yet^^

By the way, my method is not perfect, as I made some copy/paste of internal Nextcloud code. I think a better idea would be to modify the "core" part of Nextcloud to set the skeleton creation as an event triggered on first login.

(Executed with:
```php
\OC::$server->getEventDispatcher()->dispatch(IUser::class . '::firstLogin', new GenericEvent($user));
```
)

Ths way, there would be no need to redo the same job in this plugin
