### ISSUE TITLE
Can't login with Saml

### ISSUE THREAD

**Issue by jsargent7089** [nextcloud/user_saml#178]
[Saml.pdf](https://github.com/nextcloud/user_saml/files/1662615/Saml.pdf)

### Steps to reproduce
login

### Expected behaviour
login

### Actual behaviour
Account not provisioned.

Your account is not provisioned, access to this service is thus not possible.

### Server configuration

**Operating system**:
ubuntu
**Web server:**
Apache
**Database:**
Mysql
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
13.0
**Where did you install Nextcloud from:**
nextcloud.com

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here

Error | user_saml | Signature validation failed. SAML Response rejected | a few seconds ago
-- | -- | -- | --
Error | user_saml | invalid_response | a few seconds ago
Error | user_saml | Signature validation failed. SAML Response rejected | a minute ago
Error | user_saml | invalid_response | a minute ago
Error | user_saml | Signature validation failed. SAML Response rejected | 2 minutes ago
Error | user_saml | invalid_response | 2 minutes ago
Error | user_saml | Signature validation failed. SAML Response rejected | 14 minutes ago
Error | user_saml | invalid_response | 14 minutes ago
Error | user_saml | Signature validation failed. SAML Response rejected | 17 minutes ago
Error | user_saml | invalid_response | 17 minutes ago
Error | user_saml | Signature validation failed. SAML Response rejected | 18 minutes ago
Error | user_saml | invalid_response | 18 minutes ago
Error | user_saml | Signature validation failed. SAML Response rejected | 18 minutes ago
Error | user_saml | invalid_response


```
My IDP Providor is Auth0

#### Browser log
```
Insert your browser log here, this could for example include:
c) ...
```

**Comment by inem88** [comment]
Have you any results of this bug ?

**Comment by jsargent7089** [comment]
I haven't had luck on fixing it

**Comment by schiessle** [comment]
@jsargent7089 Did you tried the latest version of the saml_app. We improved the error reporting there, so you could check the log file to see if there is any useful information. As a general hint: Sometimes the attribute you map to the UID isn't communicated correctly by the IdP. You can use tools like the "saml tracer" Firefox plugin to check if all the attributes are transmitted correctly and try a different attribute as UID in case it is empty.
