### ISSUE TITLE
Add support for mapping user home

### ISSUE THREAD

**Issue by klada** [nextcloud/user_saml#202]
User backends may provide custom home directories for users (through `getHome()`), so they don't need to be stored under `datadirectory/$uid`. The `user_ldap` app already supports this by mapping an LDAP attribute to the user's Nextcloud home.

It would be nice if custom user home locations could also be implemented in the `user_saml` app through an _optionally_ mapped attribute.

### Implementation

I already have an idea how this could be implemented in a backwards-compatible way:

1. Add a `home_directory` column to the `user_saml_users` table
2. Implement mapping from variable (SAML or env variable) to `home_directory` and store it in database
3. Implement `\OCA\User_SAML\UserBackend->getHome($uid)` with the following logic:
   -  If value of `home_directory` is empty, return `false` (which means we should fall back to the default location for backwards compatibility)
   - If the value is set, then return it (obviously)

I can try to come up with a PR for this, but only if there is some feedback available if this is feasible or not.

**Comment by MorrisJobke** [comment]
cc @schiessle @rullzer How does this sound? For me it makes sense to also provide the option to pass over this attribute, like what we do with LDAP.

Maybe someone from @nextcloud/ldap can give some hints about potential pitfalls.

**Comment by schiessle** [comment]
Sounds interesting and as we already do it with LDAP I don't see a reason not to have it in the saml app.

@klada a pull request would be really great. :slightly_smiling_face:  This way we can test it, look for possible pitfalls and merge it if it is ready. Maybe you can also look at the LDAP code to get some inspiration, but in general I think the approach you outlined sounds reasonable.

**Comment by blizzz** [comment]
One thing with LDAP was the deletion process. When we can cleanup a user in  Nextcloud, it is already gone from LDAP. But the final user:delete should clean up… so in LDAP we keep track of the home folder in the preferences… the deletion process is wacky for external backends. Not sure how/whether this is supported by user_saml currently.

**Comment by klada** [comment]
Thanks everybody for the input, I'll try to come up with an implementation soonish.

@blizzz Good point about the cleanup, I'll keep an eye on it. From my experience `user:delete` works without any issues with `user_saml`.

**Comment by klada** [comment]
I have created an intial PR, please tell me what you think. This is a little checklist: 

- [x] Backend part
- [x] Admin UI for setting up mapping
- [x] Backwards compatibility (if mapping is not set up, fall back to default home dir)
- [x] Deleting users and user directories (with and without custom home directory)
- [ ] Translation
- [ ] Tests (I need help there)

There is one thing that came to my mind: With my current implementation the user's home directory may change any time, just like the display name. This is probably not a good idea, because when the IdP somehow screws up the mapping (even temporarily) this might end up in a mess for existing users.

Since this mapping is more static than a display name or an email address it might be more clever to only allow setting a custom home directory when **creating new users**. This way we would make sure that we do not break existing shares and files through some improperly set up mapping. Any thoughts on this?

**Comment by pasikarkkainen** [comment]
@klada : sounds good with setting up the home dir mapping when creating new users. Maybe add a config option to allow updating the home dir for existing users (if it has changed) ?
