### ISSUE TITLE
Github tag 

### ISSUE THREAD

**Issue by gaetandossantos** [nextcloud/user_saml#211]
On every officiel applications in nextcloud repository, we can clone repository with the same tag as the core.
In the user_saml repository, tags stop at v12.0.0beta2.

Il there a chance that you put the same tag as core like the others applications?

Gaétan

**Comment by joshtrichards** [comment]
This is not the case today. I don't believe it was then either, but the versioning was a little funny due to the transition so it may be been more buried than normal.
