### ISSUE TITLE
user_saml under nextcloud 13 + CAS "401 Unauthorized"

### ISSUE THREAD

**Issue by mohsensaeedi** [nextcloud/user_saml#217]
Hi

I asked these question a few days ago on help.nextcloud.com and no one answered me. I think it might be a bug. 

I’m attempting to use user_saml with NextCloud 13 and I want to integrate our user-login with CAS server (we use Jasig CAS as CAS service).

I use below link to config NextCloud with Apache CAS module on CentOS 7:
[https://docswiki.newro.co/index.php/Nextcloud_external_auth](url)

Current state:
 * Go to NextCloud URL
 * Get redirected to CAS login screen
 * successful login
 * Get redirected to index.php/login and NextCloud shows HTTP 401 error:
>Unauthorized
This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn’t understand how to supply the credentials required.

I don’t know why this happens. My settings are as follows:

NextCloud OpenLDAP Config:

    "user_ldap": {
            "_lastChange": "1527840328",
            "cleanUpJobOffset": "0",
            "enabled": "yes",
            "installed_version": "1.3.1",
            "ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "ldap_base": "ou=People,dc=domain,dc=com",
            "ldap_base_groups": "ou=People,dc=domain,dc=com",
            "ldap_base_users": "ou=People,dc=domain,dc=com",
            "ldap_configuration_active": "1",
            "ldap_display_name": "cn",
            "ldap_dn": "cn=ldap_user,ou=People,dc=domain,dc=com",
            "ldap_email_attr": "mail",
            "ldap_expert_username_attr": "uid",
            "ldap_group_filter": "",
            "ldap_host": "127.0.0.1",
            "ldap_login_filter": "(&(uid=%uid)(dcAccountstatus=Active))",
            "ldap_login_filter_mode": "1",
            "ldap_loginfilter_username": "0",
            "ldap_port": "389",
            "ldap_user_filter_mode": "1",
            "ldap_userfilter_objectclass": "dcMailUser\nposixAccount",
            "ldap_userlist_filter": "(|(objectclass=dcMailUser)(objectclass=posixAccount))",
            "types": "authentication"
        },

NextCloud user_saml config:

    "user_saml": {
            "enabled": "yes",
            "general-allow_multiple_user_back_ends": "0",
            "general-require_provisioned_account": "0",
            "general-uid_mapping": "HTTP_CAS_USER",
            "installed_version": "1.5.0",
            "type": "environment-variable",
            "types": "authentication"
        },

Apache mod_auth_cas under vhost section:

    CASVersion 2
        CASLoginURL https://accounts.domain.com/cas/login
        CASValidateURL https://accounts.domain.com/cas/serviceValidate
        CASTimeout 28800
 
        <Location "/index.php/login">
                AuthType CAS
                AuthName "CAS Authentication"
                require valid-user
        </Location>
 
 
        <Location "/index.php/apps/user_saml/saml/login">
                AuthType CAS
                AuthName "CAS Authentication"
                require valid-user
        </Location> 

I changed below setting on user_saml to 1 but the result was the same:

    "general-allow_multiple_user_back_ends": "0",
     "general-require_provisioned_account": "0",

I don't know it's bug or some problem on my configuration. After searching a lot I cloud not find the right answer.

### Steps to reproduce
1. Configure jasig CAS 5.2 as SSO Service
2. Configure NextCloud with OpenLDAP 
3. Configure User_saml with environment variable
4. Configure Apache with cas module

### Expected behaviour
Use nextcloud after successfully authenticate with CAS Service and redirect to nextcloud without any error

### Actual behaviour
Nextcloud show below error after successful login on cas service and redirect back to nextcloud
>Unauthorized
This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn’t understand how to supply the credentials required.

### Server configuration

**Operating system**:
CentOS 7.5 x86_64

**Web server:**
Apache (It's possible to use nginx if it can solve these problem)

**Database:**
MariabDB

**PHP version:**
PHP 7.1

**Nextcloud version:** (see Nextcloud admin page)
13

**Where did you install Nextcloud from:**
Official version that is available on nextcloud.com

**List of activated apps:**

```
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - drawio: 0.8.9
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.8.1
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - onlyoffice: 1.3.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - rainloop: 5.0.6
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - user_saml: 1.5.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_pdfviewer
  - user_external

```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mbs.co.ir:8443",
            "accounts.mbsco.ir"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.mbs.co.ir:8443",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

```

### Client configuration
**Firefox or Google chrome**

**Operating system:**
Fedora 28

#### Nextcloud log (data/owncloud.log)
```
no error log when problem occur
```

**Comment by mohsensaeedi** [comment]
Is it a bug or wrong configuration?

**Comment by brtptrs** [comment]
NC + user_saml + CAS works for me (mostly) with this configuration:
Apache:
```
      <location /index.php/apps/user_saml/saml/login>
        AuthType CAS
        require valid-user
      </location>
```

user_saml:
```
        "user_saml": {
            "enabled": "yes",
            "general-allow_multiple_user_back_ends": "1",
            "general-idp0_display_name": "Intranet Login",
            "general-uid_mapping": "REMOTE_USER",
            "installed_version": "1.5.0",
            "type": "environment-variable",
            "types": "authentication"
        },
```
NC14 with this setup causes an "ERR_TOO_MANY_REDIRECTS" error
See #248

**Comment by pierreozoux** [comment]
NC14 is not longer supported, feel free to reopen if you still have the issue.
