### ISSUE TITLE
MS ADFS guide

### ISSUE THREAD

**Issue by MichaelHeimann** [nextcloud/user_saml#23]
Hi,

I've seen you support SAML and immediately wanted to enable it - but failed.

I've tried to configure MS ADFS 3 as IDP with user_saml as SP and got the redirect working and as far as I can see the authentication was granted from the server but I only see "invalid_response Not authenticated" in the browser.

Help like how to configure the claim rule on an ADFS setup would be appreciated.
e.g. http://www.cisco.com/c/en/us/support/docs/unified-communications/unified-communications-manager-callmanager/118771-configure-samlsso-00.html

Also enabling to import IDP metadata to set config values correctly would be nice.

Cheers,
Michael

**Comment by LukasReschke** [comment]
Hi Michael

Thanks for giving the app a try. While I didn't test ADFS I'm pretty sure it should work, can you screenshot me your settings? I can then try to test it locally as well and document that properly :-)

Thanks a lot,
Lukas

**Comment by MichaelHeimann** [comment]
Hi Lukas

thanks for your response. Which settings would you be interested in?

This is how the user_saml settings in nextcloud look like.
×

​
I am getting redirected to the ADFS login page, but after authenticating I
only get :
"

invalid_response

Not authenticated

"

:(

This is what I can do on ADFS to get attributes in the SAML info from ADFS:


×

​

This is what SAML tracer addon in firefox gives me:


<samlp:Response ID="_dbde8760-bbc1-4c6f-9bc2-4580f41f4e9c"
                Version="2.0"
                IssueInstant="2016-07-10T20:03:37.657Z"

Destination="https://share.avodaq.com/index.php/apps/user_saml/saml/acs"
                Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
                InResponseTo="ONELOGIN_79ce41b9d4eaef90d6f09d6ac3c6eeec1f221577"
                xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                >
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://adfs.avodaq.com/adfs/services/trust</Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <Assertion ID="_5ef66942-f4ee-48f5-9c3c-0a4ffcf020af"
               IssueInstant="2016-07-10T20:03:37.656Z"
               Version="2.0"
               xmlns="urn:oasis:names:tc:SAML:2.0:assertion"
               >
        <Issuer>http://adfs.avodaq.com/adfs/services/trust</Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
                <ds:CanonicalizationMethod
Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                <ds:SignatureMethod
Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
                <ds:Reference URI="#_5ef66942-f4ee-48f5-9c3c-0a4ffcf020af">
                    <ds:Transforms>
                        <ds:Transform
Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                        <ds:Transform
Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </ds:Transforms>
                    <ds:DigestMethod
Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />

<ds:DigestValue>ctZdsLXmWYI+5fkUUJdE1OHthdI=</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>(...)</ds:SignatureValue>
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>(...)</ds:X509Certificate>
                </ds:X509Data>
            </KeyInfo>
        </ds:Signature>
        <Subject>
            <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <SubjectConfirmationData
InResponseTo="ONELOGIN_79ce41b9d4eaef90d6f09d6ac3c6eeec1f221577"
                                         NotOnOrAfter="2016-07-10T20:08:37.657Z"

Recipient="https://share.avodaq.com/index.php/apps/user_saml/saml/acs"
                                         />
            </SubjectConfirmation>
        </Subject>
        <Conditions NotBefore="2016-07-10T20:03:37.653Z"
                    NotOnOrAfter="2016-07-10T21:03:37.653Z"
                    >
            <AudienceRestriction>

<Audience>https://share.avodaq.com/index.php/apps/user_saml/saml/metadata</Audience>
            </AudienceRestriction>
        </Conditions>
        <AttributeStatement>
            <Attribute Name="uid">
                <AttributeValue>mheimann</AttributeValue>
            </Attribute>
        </AttributeStatement>
        <AuthnStatement AuthnInstant="2016-07-10T20:02:15.039Z">
            <AuthnContext>

<AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</AuthnContextClassRef>
            </AuthnContext>
        </AuthnStatement>
    </Assertion>
</samlp:Response>

Thanks for your help,


Michael




2016-07-09 10:40 GMT+02:00 Lukas Reschke <notifications@github.com>:

**Comment by LukasReschke** [comment]
> This is how the user_saml settings in nextcloud look like.
> ×

Uploading images via mail does sadly not work. Can you repost your image via the web page? THX a lot!

**Comment by MichaelHeimann** [comment]
Sorry, didn't know that.
Updated my posting with the images.

Cheers,
Michael

2016-07-11 9:18 GMT+02:00 Lukas Reschke <notifications@github.com>:

**Comment by parryjacob** [comment]
Did you make any further progress on this? I found that ADFS was rejecting the certificate I gave to Nextcloud, so I set ADFS to not check revocation status on it.

After getting the certificate to work, it seems as though ADFS defaulted to using SHA-256 and was complaining about getting its replies in SHA-1, so changing the algorithm in the Advanced tab for the RP in the ADFS management console got past that error.

Once those are sorted out, it seems as though it gets stuck in a redirect loop, and eventually ADFS fails the process.

I will continue to look into it and let you know if I find any solutions.

**Comment by parryjacob** [comment]
@MichaelHeimann 

After much hassle, I've gotten this to work.

ADFS: https://f.jacobparry.ca/2016/09/GwioCU71NWPL.png

For the LDAP attributes in that screenshot, Given Name and Surname are selected from the list, and I typed sAMAccountName in.

The really important part that I believe you are missing is the 1st Issuance Transform Rule, where I associate the SAM-Account-Name LDAP attribute with the Name ID outgoing claim type.

Nextcloud config: https://f.jacobparry.ca/2016/09/64r5fys0g9wt.png

Under "Service Provider Data" I have a generated cert+key pair that is supposedly trusted by ADFS, although as stated above that gives me nothing but errors.

You will have to run the following in an Administrator Powershell prompt on your ADFS server:

```
Set-ADFSRelyingPartyTrust -EncryptionCertificateRevocationCheck None -SigningCertificateRevocationCheck None -TargetName <your RP name>
```

If the cert/key you use is actually globally trusted, you may not have to do that but I did.

As well, under "Hide optional Identity Provider settings..." be sure to copy your token signing certificate (in PEM format) into the appropriate box there as well (you can get that autogenerated certificate from the ADFS management tools).

I should note that the attribute under "General" is the name of the Outgoing Claim Type I chose when I configured the rules for my SP, as shown in the ADFS screenshot.

**Comment by MichaelHeimann** [comment]
@parryjacob 

Thanks for reminding me to work on this again!

I basically copied your settings (which was enabling alot of the security settings check-boxes).
Unfortunately it didn't change a thing.

But when I'm already on it I read your hassle with the certificates, so I thought certs are a common source of pain. In my installation I thought I could strike this out since ADFS and nextcloud both use the SAME certificate (wildcard). 

Anyways, after reading your post for the 5th time or so, I found out that the certificate under "optional Identity Provider Settings" is not the "service communications" cert from ADFS but the token signing cert! Woha! And then finally it works!.

Sorta. No logout, and sadly, also no SSO.

With no SSO I mean that although I'm already logged into coporate sites I still get the user and password promt from ADFS. I can login successfully, but it's not SSO.
Basically this is a different login screen now for me - no user benefit.

I *think* this might be because nextcloud is asking only for forms based auth. I came to that conclusion after rading [this](https://wiki.servicenow.com/index.php?title=Configuring_ADFS_2.0_to_Communicate_with_SAML_2.0#Workaround:_Supporting_Kerberos_Authentication) page talking about adding Kerberos to possible auth ways.

So, I patched (...)nextcloud/apps/user_saml/3rdparty/vendor/onelogin/php-saml/lib/Saml2/AuthnRequest.php line 105 from
<saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>

to 

<saml:AuthnContextClassRef>urn:federation:authentication:windows</saml:AuthnContextClassRef>

which did the trick for me.

@LukasReschke 
There's surely a nicer way. could you help me find it? If not, could you add a checkbox for that?

So: happy now!

Cheers,
Michael

**Comment by LukasReschke** [comment]
> There's surely a nicer way. could you help me find it? If not, could you add a checkbox for that?

That should be possible. I'd however prefer to do that automatically without user intervention.

Can I ask you to test https://github.com/nextcloud/user_saml/pull/38 and report back there whether that helped?

Just as a disclaimer: Note that I don't have a Windows server to test against with ADFS and unless this becomes a [customer requirement](https://nextcloud.com/enterprise/), it won't be something we officially support. 

Which means it *may* work but it's not something we test against, but there's always the chance to either vote for it either by contributing yourself or paying for it 😉

**Comment by Fr3llD** [comment]
@Lukas, did it became supported? In the Nextcloud documentation it says;

> The following providers are supported and tested at the moment:

>    SAML 2.0
  >          OneLogin
  >          Shibboleth
  >          Active Directory Federation Services (ADFS)

It's mentioned here;
https://docs.nextcloud.com/server/11/admin_manual/configuration_server/sso_configuration.html

btw, that documentation could be improved, If I can get it to work I might look into that.

**Comment by bluewalk** [comment]
Followed all instructions mentioned in this issue, but I'm still stuck at
```
invalid_response

Not authenticated
```

Is there a concise guide on setting up ADFS integration?

**Comment by LukasReschke** [comment]
As this seems to be a setup issue please ask such questions at help.nextcloud.com. Thanks a lot!
