### ISSUE TITLE
Where Are You From (WAYF) support

### ISSUE THREAD

**Issue by kosli** [nextcloud/user_saml#243]
Are there any plans to support a WAYF? see https://www.switch.ch/aai/support/tools/wayf/

How are others handling the case when you have users from multiple identity providers?

**Comment by pautri** [comment]
You can set up a separate SP that uses your discovery service and then configure Nextcloud to use an environment variable for authentication. You may have to map several attributes to your environment variable in the SP config to ensure that you always get some sort of user ID, it depends a bit on how uniform the attribute release of the identity providers is.

**Comment by kosli** [comment]
Thanks @pautri for the idea. Do you have there a sample configuration or howto with more information on how to do it?

**Comment by pautri** [comment]
Here's an example config for a Shibboleth SP: https://github.com/clarin-eric/SPF-tutorial/blob/master/shibboleth2.xml
The REMOTE_USER will then be available as the environment variable in Nextcloud.
As you cannot trigger the Shibboleth session from Nextcloud in such a setup, you need to use an "active" setup where the Shibboleth session is always triggered when your Nextcloud URL is visited. (requireSession true in Apache Shibboleth settings for your vhost or whatever config you use).

**Comment by jagland** [comment]
I use the following in Apache to call Shibboleth SP for Nextcloud
```
                <Location /index.php/apps/user_saml/saml/login>
                Require valid-user
                AuthType shibboleth
                ShibRequestSetting requireSession 1
		</Location>
```
It's best to make sure that `/index.php/login?direct=1` is not subject to the above, so that you can still login as local "admin" user.

**Comment by kosli** [comment]
@pautri  @jagland 
Thanks for your help. I had missed the "environment variables" option of the module as it is ONLY visible the first time until you select either SAML or ENV...
Finally I got it working!!! Thanks a lot!

**Comment by kosli** [comment]
@jagland 
seems still something is not fine. when i access the cloud for the first time (no shib and no user session, e.g. incognito browser window), i get redirected to the SP/WAYF page, get redirected to the IdP page. After logging in on the IdP page, i get redirected to an URL simliar to the one:
` /index.php/apps/user_saml/saml/login?requesttoken=xjWVu7ISRVVgq7oItszodg5NKLV1mJm7dYLyU1THQv4%3D%3Ai13B/tR9an5YmOt89P3dOj8cQZoC39jSJ8WjeGC2bY8%3D&originalUrl=&idp=1`
whereas the browser shows "The page isn’t redirecting properly".
When I access the main URL of the cloud again, I am logged in and everything is working as expected. Any idea what is causing that issue? 

P.s.: Thanks for the hint with the `/index.php/login?direct=1`

**Comment by kosli** [comment]
@jagland  @pautri 
any idea why i get the blank page after succesfull logon and need to access the root URL again? (see above). do you have the same issue? an upgrade to user_saml 2.0 app didnt't help.

**Comment by kosli** [comment]
@jagland @pautri @LukasReschke @schiessle 
could the blank page after logon be due to the originalUrl parameter being empty and so the user doesn't get redirected to the main page/root url? any idea how to "resolve" this?

**Comment by pautri** [comment]
we did not have this issue. In the SP config, in the sessions element, there is an attribute "relayState" that determines how the original location is passed on. There are three options, see https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPSessions (one option is to leave it out).
We are using the "ss:mem" option. Perhaps you could try experimenting with that.

**Comment by kosli** [comment]
fyi, after upgrading to NC 17.0.3 and the user_saml plugin 2.4.2 I have no more the issue with the blank page after returning from the wayf & idp login screen. I will close the issue and re-open in case this error would occur again. Thank you all for the help.
