### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by erosinger** [nextcloud/user_saml#244]
Hey All,

Thanks for providing this great feature.
As I am relativley new to SSO and SAML, I would love to reach back to some documentation.
Anything I find online is either outdated or "file not found" for my version of Nextcloud 13.

Where would you recommend me to go looking?

I am trying to setup SSO with SAML against an Azure Active Directory (WestEurope) with a Nextcloud 13 installed from tar-package on an Ubuntu with NFS (Azure File Storage) and a mysql-db on localhost.

Looking forward to your responses.

Best,
Enno

**Comment by erosinger** [comment]
This is still a major issue. Even after the Release of NC 14 and the SAML SSO App beeing updated "vor 3 Wochen, 4 Tage" (3 weeks and 4 days). Any idea whats going on here?

**Comment by timm2k** [comment]
Supplied link at App Store points to non existing site:
https://docs.nextcloud.com/server/13/admin_manual/configuration_server/sso_configuration.html

**Comment by jagland** [comment]
#242 might not have been created if documentation were better.

**Comment by MariusBluem** [comment]
SSO/SAML is documented in our enterprise portal over here: https://portal.nextcloud.com/article/configuring-single-sign-on-10.html

**Comment by mactrent** [comment]
@MariusBluem Moving the documentation into a paid portal may be as it may, but it seems the "Admin Documentation" link that @timm2k mentions should be removed from the package's app listing or updated to point there.  A dead link does nobody any good.

**Comment by mactrent** [comment]
For what it's worth, @erosinger :
[NC 12 documentation](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/sso_configuration.html) for this, linked on the repository's home page.  It's not a how-to-guide (nor does a cursory search show one on [Discourse](https://help.nextcloud.com/c/How-to-FAQs)), but it's not really outdated either - see [Change list from stable12](https://github.com/nextcloud/user_saml/compare/stable12?diff=unified).

**Comment by MariusBluem** [comment]
Thanks for the feedback. I will improve this in our documentation.

**Comment by erosinger** [comment]
Thank @mactrent  and @MariusBluem for responding and sorry for the late reply. I will try to work with the provided docs and find a solution. We had the nextcloud topic on hold for a while internally but are now back on track integrating it into our larger solution. All the best

**Comment by erosinger** [comment]
> @MariusBluem Moving the documentation into a paid portal may be as it may, but it seems the "Admin Documentation" link that @timm2k mentions should be removed from the package's app listing or updated to point there. A dead link does nobody any good.

Agree to that 👍 Compromise would be to include some descriptive information about the reason that it is not available. In my opinion it is ok to hide things behind a paywall, when they are very crucial
