### ISSUE TITLE
NC14 + user_saml causes ERR_TOO_MANY_REDIRECTS errors

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/user_saml#248]
### Steps to reproduce
1. Set up NC14 with user_saml and "environment-variable" configuration
2. Log in 
3. Authenticate against a CAS server

### Expected behaviour
The user gets authenticated and is logged in on NC 14
This works fine on NC 13

### Actual behaviour
The browser throws an "ERR_TOO_MANY_REDIRECTS" error
Reloading the page completes the login process and the user can continue normally

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 14.0.0

**Where did you install Nextcloud from:** Download fron nextcloud site

**user_saml config:**
        "user_saml": {
            "enabled": "yes",
            "general-allow_multiple_user_back_ends": "1",
            "general-require_provisioned_account": "0",
            "general-uid_mapping": "REMOTE_USER",
            "installed_version": "1.6.2",
            "type": "environment-variable",
            "types": "authentication"
        },

### Client configuration
**Browser:** Chromium and Firefox

**Operating system:** Ubuntu

**Comment by TheElbenreich** [comment]
Got the same problem over here. Although on Safari only.

**Comment by TheJonny** [comment]
I also have this problem.

Reload by F5 in firefox does not log me in, but pressing Enter in the url-bar works. the only differences in these requests are the Referer-Header and that that the latter has the Cookie `nc_sameSiteCookiestrict=true`.

- Replacing the Referer header in the apache configuration did not change anything
- Forcing the cookie made it work
```
<Location /nextcloud>
RequestHeader edit Cookie "$|; nc_sameSiteCookiestrict=true" "; nc_sameSiteCookiestrict=true"
</Location>
```

**Comment by TheJonny** [comment]
so i think for me its the same issue as #169 .

**Comment by brtptrs** [comment]
This one liner seems to solve our problem
#147

**Comment by solracsf** [comment]
Fixed by https://github.com/nextcloud/user_saml/pull/379
