### ISSUE TITLE
Can't save basic sharing settings, when this app is active 

### ISSUE THREAD

**Issue by ci2014** [nextcloud/user_saml#25]
When the SAML app is activated, changes made to the /index.php/settings/admin#shareAPI page, are not being saved. 

This caused several problems.

**Comment by blizzz** [comment]
Nextcloud 10 will most likely not be affected, because of architectural change in the admin page. These settings are now split up.

Nevertheless possibly valid for Nc 9.

**Comment by LukasReschke** [comment]
Assuming that this is fixed in Nextcloud 10 I'll close this.
