### ISSUE TITLE
Can't get access with SSO - "Account not provisioned"

### ISSUE THREAD

**Issue by nnyf96** [nextcloud/user_saml#258]
**Steps to reproduce**

1. Configured the SSO with this [Manual](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/sso_configuration.html)
2. In my Security Settings i only use „Indicates whether the <samlp:AuthnRequest> messages sent by this SP will be signed. [Metadata of the SP will offer this info]“

**Expected behaviour**

The IDP response with correct username and password. The nextcloud storage from this user should be open. 

**Actual behavior** 

I can use the SSO form my IDP. The IDP gave me the right mailaddress with given and surname, but when i use this to get access to the nextcloudstorage i got this response: 
„Account not provisioned.
Your account is not provisioned, access to this service is thus not possible.“
I can‘t find something in my nextcloud.log file.

**Server configuration**

Operating system: Linux 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64
Webserver: Apache/2.4.29 (Ubuntu) (apache2handler)
Database: mysql 5.7.24
PHP version:
7.2.10-0ubuntu0.18.04.1 Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, mcrypt, Zend OPcache
Nextcloud version: 14.0.3 – 14.0.3.0

**Where did you install Nextcloud from:**

From the official Nextcloud homepage with the web install client

**List of activated apps:**

Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - issuetemplate: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_saml: 2.0.0
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

**Nextcloud configuration**

        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "ol-nextcloud-projekt.hs-woe.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "overwrite.cli.url": "http:\/\/ol-nextcloud-projekt.hs-woe.de\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"

**Logs:**

All logs are empty.

**Comment by mathiasconradt** [comment]
What IdP are you using? ADFS? Valid certificate put in the Nextcloud config? I also suggest to put the SAML config in here as well.
Nextcloud itself offers configuration support via subscription if needed (https://nextcloud.com/pricing)

**Comment by nnyf96** [comment]
With the new Version (2.1.0) I got an error message in the error log. My problem was a wrong urn:oid.
