### ISSUE TITLE
Theme buttons

### ISSUE THREAD

**Issue by schiessle** [nextcloud/user_saml#259]
Right now the buttons in the "chose login options" screen are always Nextcloud-blue, hardcoded here: https://github.com/nextcloud/user_saml/blob/master/css/selectUserBackEnd.css#L11

Would be nice if they would use the colors defined in the Theme settings

![image](https://user-images.githubusercontent.com/1589737/48207535-1ea8f900-e371-11e8-8ae5-495b079caafc.png)

cc @nextcloud/designers what's the best/easiest way to fix this?

**Comment by skjnldsv** [comment]
use the css variable: https://github.com/nextcloud/server/blob/master/core/css/css-variables.scss
`var(--color-primary-element)`
