### ISSUE TITLE
Feature Request: Allow to customize "Direct log in" button label

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/user_saml#280]
When enabling SAML/SSO and direct login, the login page shows two buttons with options _"Direct Login"_ and _"SSO / SAML Login"._

Would be good if the button labels can be configured, because the terms are quite technical. In real case scenarios, there are usually certain use cases, where other button labels would make more sense and would be easier to understand to non-tech people, such as:

> Login as internal user / Login as external user

or

> Login with your XYZ account / Login as external user

or alike. If the labels could be customized, it would give the admin all the freedom he needs.

**Comment by va1entin** [comment]
I think this feature is missing only until NC version <=13.
In the current user_saml version for at least NC 14 a name for the identity provider can be configured, which also changes the button label:

![image](https://user-images.githubusercontent.com/31535155/50898974-086ef600-1411-11e9-9c4d-3d196b5ffa94.png)

It looks like this:

![image](https://user-images.githubusercontent.com/31535155/50899133-8501d480-1411-11e9-82e6-f53caee1cc9b.png)

**Comment by va1entin** [comment]
@tonyfairbanks That's correct. The initial issue doesn't specify that it's only about the direct login button though, which is why I pointed out that at least the SSO button label can be configured. +1 for customization of the direct login button label.

**Comment by acsfer** [comment]
Have you tried:

`./occ config:app:set user_saml directLoginName --value="Your value here"`

**Comment by blizzz** [comment]
as @acsfer  pointed out, already implemented in 7f7def4b7f21fabf34b7921bbdc344cde9a9d88d, closing.
