### ISSUE TITLE
SAML & LDAP - mail attribute not populated

### ISSUE THREAD

**Issue by maghog** [nextcloud/user_saml#282]
When login using SAML the mail attribute never gets populated/updated.
Login using LDAP works as expected and the mail attribute gets populated/updated.

Is this a known limitation? It's a severe issue because the user mail address is needed in Nextcloud (share, Talk...)
 
Nextcloud 14.04
LDAP 1.4.0
SAML 2.1.0

**Comment by ChristophWurst** [comment]
cc @blizzz @schiessle
