### ISSUE TITLE
NextCloud PHP Version 7.3 Breaks SAML plugin

### ISSUE THREAD

**Issue by ataraxus** [nextcloud/user_saml#325]
### Steps to reproduce
1. use latest nextcloud docker image  (15.0.7.0)
2. follow this setup of saml (https://stackoverflow.com/questions/48400812/sso-with-saml-keycloak-and-nextcloud) really great
3. be stuck for 3 evenings debugging the setup 

### Expected behaviour
Login through saml 

### Actual behaviour
Server issue like https://github.com/nextcloud/user_saml/issues/324
here is the hint which helped me to understand the issue: https://github.com/onelogin/php-saml/issues/349

I "downgraded" to nextcloud 14.0.10.0 were the setup works like expected. 

**Operating system**:
Ubuntu 18.04 Docker 
**Web server:**
working
docker image: nextcloud:14.0.10
broken: 
docker image: nextcloud:latest
**Database:**
MYSQL
**PHP version:**
working 7.2
broken 7.3

**Comment by Kosyne** [comment]
Does 15.0.7 work with php 7.2? I get the same issue with a similar setup and was gonna give that a shot when I got the time.

**Comment by Toilal** [comment]
You may also disable response signing inside your SAML idp, if it's an option for you.

**Comment by ataraxus** [comment]
@Toilal did it worked for you. I did that but then run in anouther issue... now i'm on 14 I wonder if its still broken in version 16. 
 
anyhow it should be an an either security or functionality ;)

**Comment by jabouchleih** [comment]
As @pfy mentioned in my issue, it has been fixed with the latest version 2.2.0.

**Comment by ataraxus** [comment]
@jabouchleih thanks for the heads up
