### ISSUE TITLE
Compatibility with NC 16

### ISSUE THREAD

**Issue by saibotk** [nextcloud/user_saml#328]
Hello, 

I just upgraded to Nextcloud 16 and the app is automatically disabled as it is flagged incompatible.

I would appreciate if we could resolve this issue.

Thank you

**Comment by in0rdr** [comment]
I know this issues is closed. However, I encountered the same situation and the following manual `app:update` fixed it for me:
```
# sudo -u apache php occ app:update user_saml
user_saml new version available: 2.2.0
user_saml updated
```
Even thouhgh, I updated the App in the Nextcloud Admin Web-Interface (to version `2.2.0`) beforehand, the app was only updated after I updated the app from command line.
