### ISSUE TITLE
Not allowing to save 

### ISSUE THREAD

**Issue by barinder** [nextcloud/user_saml#35]
Hello I am trying to configure user_saml app with LDAP and Shibboleth, but getting "invalid_response Not authenticated" error.

I chain of certificates while user_saml app's setting is only allows to save only one certificate.

i.e. only one

-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

block is allowed, while I have chain of certificates. 

This might be a bug or missing feature in user_saml app.

**Comment by MorrisJobke** [comment]
cc @lukasreschke

**Comment by LukasReschke** [comment]
This has been resolved via email. The problem has been that the configured IdP certificate needs to be the one used for signing and not the one used for the HTTPS connection.
