### ISSUE TITLE
Blank settings page in nextcloud 17

### ISSUE THREAD

**Issue by manul57** [nextcloud/user_saml#370]
### Steps to reproduce
1. Install and enable SSO & SAML authentication app from the market
2. Click on the Settings for SSO & SAML authentication 

### Expected behaviour
I should see the setting form of the app

### Actual behaviour
The page is blank (in the page source I see all the form is hidden by css)

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
 Apache/2.4.29

**Database:**
Mysql 5.7.27

**PHP version:**
PHP 7.2.23

**Nextcloud version:** (see Nextcloud admin page)
17.0.1.1

**Where did you install Nextcloud from:**
From the nextcloud website

**List of activated apps:**

  - accessibility: 1.3.0
  - activity: 2.10.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "proxy": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/var\/log\/nextcloud\/mylog.log",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [
            "twofactor_rcdevsopenotp",
            "gluusso",
            "defaultgroup"
        ],
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}

### Client configuration
**Browser:**
Firefox 71.0

**Operating system:**
Windows 10

#### Nextcloud log (data/owncloud.log)
No errors

#### Browser log
TypeError: data.ocs is undefinedadmin.js:19:9
    init admin.js:19

**Comment by lunika** [comment]
Do you still have the problem ?

**Comment by lunika** [comment]
In my case it was a reverse proxy issue. Nginx was not able to found this app assets resulting in a blank page.

**Comment by waza-ari** [comment]
Hm, I have exactly the same issue. Running Nextcloud 17.0.1 in a docker container. All apps and settings work, just SSO & SAML for some reason shows a blank error page. 

@lunika when you say it was a reverse proxy issue - could you tell more about it? Thanks!

**Comment by jvinolas** [comment]
I'm facing the same problem with Nextcloud 21.0.0 after installing user_saml plugin.
This errors arise at the browser console: .../apps/dashboard/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)

Any hints on how to fix this?

![imatge](https://user-images.githubusercontent.com/2132863/113729033-eb602500-96f6-11eb-9c95-98b61feb93d0.png)

**Comment by waza-ari** [comment]
Sorry I didn't comment my fix earlier. For me it was simply a file permission problem. Double check if all PHP files belonging to Nextcloud are executable and all directories Nextcloud needs to write to are writable. Die MIME error is misleading and came from the reverse proxy in my case, as the reply did not match what it expected. The Nextcloud logs have been helpful for me
