### ISSUE TITLE
HTTP Error 405 after successfully logging in to IdP

### ISSUE THREAD

**Issue by reavessm** [nextcloud/user_saml#375]
### Steps to reproduce
1. Install SSO & SAML app
2. Set up Keycloak as IdP for Nextcloud
3. Login using Keycloak

### Expected behaviour
User will be logged in.

### Actual behaviour
On Chrome/Vivaldi: HTTP Error 405 returned from GET https://nextcloud.domain.com/apps/user_saml/saml/acs
On Firefox: User is logged in.  After checking logs, a POST to https://nextcloud.domain.com/apps/user_saml/acs returns 303 and continues normally.

Note: nextcloud/keycloak are both behind nginx reverse proxy

## Server configuration detail

**Operating system:** Debian (from container)

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** sqlite3 3.27.2

**PHP version:** 

7.3.13
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 18.0.0 RC2 - 18.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:**  Upgrade recently, but has always been a problem

**Where did you install Nextcloud from:** Docker container

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - apporder: 0.9.0
 - audioplayer: 2.8.4
 - bookmarks: 2.3.4
 - calendar: 1.7.2
 - camerarawpreviews: 0.7.3
 - carnet: 0.19.1
 - checksum: 0.4.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.6
 - cookbook: 0.5.7
 - dashboard: 6.0.0
 - dashboardcharts: 0.1.3
 - dav: 1.14.0
 - drawio: 0.9.4
 - dropit: 0.3.0
 - emlviewer: 0.0.4
 - encryption: 2.6.0
 - end_to_end_encryption: 1.1.0
 - external: 3.4.1
 - extract: 1.2.2
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_ebookreader: 0.0.1
 - files_frommail: 0.3.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - folderplayer: 14.0.0
 - forms: 1.1.0
 - issuetemplate: 0.6.0
 - keeporsweep: 0.2.1
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.2
 - metadata: 0.10.0
 - music: 0.12.1
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.1
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.0.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 1.2.3
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - user_saml: 2.4.0
 - video_converter: 0.1.2
 - viewer: 1.2.0
 - workflow_pdf_converter: 1.3.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - breezedark
 - event_update_notification
 - files_external
 - files_readmemd
 - groupfolders
 - groupquota
 - mail
 - oidc_login
 - polls
 - quota_warning
 - social
 - socialsharing_diaspora
 - socialsharing_email
 - socialsharing_facebook
 - socialsharing_twitter
 - spreed
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "sqlite3",
    "version": "18.0.0.9",
    "overwrite.cli.url": "http:\/\/nextcloud.reaves.dev",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "app_install_overwrite": [
        "maps",
        "breezedark",
        "external",
        "drawio",
        "onlyoffice",
        "ocr",
        "user_saml",
        "audioplayer",
        "calendar",
        "checksum",
        "contacts",
        "dashboard",
        "files_ebookreader",
        "files_markdown",
        "keeporsweep",
        "files_readmemd",
        "spreed",
        "carnet",
        "ocdownloader",
        "files_frommail",
        "folderplayer",
        "ocsms",
        "forms",
        "dropit",
        "end_to_end_encryption",
        "radio",
        "social"
    ],
    "has_rebuilt_cache": true
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Vivaldi "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.102 Safari/537.36 Vivaldi/2.6.1566.44"

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
> 192.168.240.1 - - [16/Jan/2020:07:32:40 -0500] "GET /index.php/204 HTTP/1.0" 204 1155 "-" "Mozilla/5.0 (Android) Nextc
loud-android/3.9.2"
> 192.168.240.1 - - [16/Jan/2020:07:32:42 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 200
1808 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
> 192.168.240.1 - - [16/Jan/2020:07:32:43 -0500] "GET /apps/user_saml/saml/login?originalUrl=&requesttoken=Dp2AiLWpPeOXZ
BrMYP8o8XD3sTz1qtZDvK%2BrlHi5AH4%3D:Ocyxu%2BKGC5fREzW2BbFNgBncy1KC7OAi5eL8zhWIWh0%3D&idp=1 HTTP/1.0" 303 1874 "-" "Mozil
la/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.102 Safari/537.36 Vivaldi/2.6.15
66.44"
> 192.168.240.1 - - [16/Jan/2020:07:32:45 -0500] "GET /apps/user_saml/saml/acs HTTP/1.0" 405 883 "-" "Mozilla/5.0 (Windo
ws NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.102 Safari/537.36 Vivaldi/2.6.1566.44"
> 192.168.240.1 - - [16/Jan/2020:07:32:47 -0500] "GET /index.php/204 HTTP/1.0" 204 1155 "-" "Mozilla/5.0 (Android) Nextc
loud-android/3.9.2"
> 192.168.240.1 - - [16/Jan/2020:07:32:47 -0500] "GET /index.php/204 HTTP/1.0" 204 1155 "-" "Mozilla/5.0 (Android) Nextc
loud-android/3.9.2"
> 192.168.240.1 - - [16/Jan/2020:07:32:48 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 200
1808 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
```
</details>

<details><summary>Nextcloud log</summary>

```
none
```
</details>

<details><summary>Browser log</summary>

Navigated to https://keycloak.domain.com/auth/realms/homelab/protocol/saml?SAMLRequest=lZJfT2IxEMXf%2BRSm79D7B7luAyQoq5IgEGF98MX09g5LY2977bSI395yu%2B6qyZo4bzOd88uZkw6R16phE%2B92%2BhaePKDrnIQ61Eojax9HxFvNDEeJTPMakDnB1pObOct6CWuscUYYRT7JvlZxRLBOGh1ls%2BmILBc%2F58ur2eJhm50NgBdC5GWa5Tzb5iWc5v1iMDg7LfJSFMWPfgllEqV3YDFwRiRgSSfSED3MNDquXZgnWdJN0m462KQZyzPW799H6TQcKzV3rXznXIOM0kd4Ecrwx54FvgfsVbCnPKRDQ69qpDtTg%2BIlfbubHo%2BNvNWf0bnUldS%2Fv06gjEvIrjebVXe1XG8iZPKWzIXR6Guwa7B7KeDX7TyaDB41HFww6asPJpsGqQ%2Fih6Oj1hblAsm4xQ6PPWuTsePvYmpwvOKOD%2Bl7yj9uwxbhvtl0ZZQUL%2B38WJfG1tz9P4a0l7YTWXW37SrzGhsQciuhIn8xE6XM80Ww6GBEnPVATui404lmPn7d8Ss%3D&RelayState=http%3A%2F%2Fnextcloud.domain.com%2Fapps%2Fuser_saml%2Fsaml%2Flogin&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=oIB8Z9pQKk5P3gERfxmsOvHUuwi3J9utNA0EgT8Nv09zX2sphpQwcQTbqtfgv%2Fb2n5ngZ1De6A5ySYklo%2FyQ6jqKWeSizbRQzsc23W04gN7kqy5FBh%2Fu%2F%2FMLN6wtcAZBL6x38yJLgH3RNw9PNnxUfepEAj6nYk4A2e0ls22qZJoGkzfkft5CPbIU3QdAKMhsvAejJI1MOKCsedMZ4fxpvkkTFhOw7PF%2Fjwv9h2eZRWtO4EMuo3TvRFb3XY0jJNzIQiNbCVDCziPZryzXPCdvCgOuKn6%2FkapOg96QnZAgsVDI8dFTjE1dz%2FOWYkwaQeJMFvsFhaAs8eqoFeb7bkgbuQ%3D%3D
saml:1 Mixed Content: The page at 'https://keycloak.domain.com/auth/realms/homelab/protocol/saml?SAMLRequest=lZJfT2IxEMXf%2BRSm79D7B7luAyQoq5IgEGF98MX09g5LY2977bSI395yu%2B6qyZo4bzOd88uZkw6R16phE%2B92%2BhaePKDrnIQ61Eojax9HxFvNDEeJTPMakDnB1pObOct6CWuscUYYRT7JvlZxRLBOGh1ls%2BmILBc%2F58ur2eJhm50NgBdC5GWa5Tzb5iWc5v1iMDg7LfJSFMWPfgllEqV3YDFwRiRgSSfSED3MNDquXZgnWdJN0m462KQZyzPW799H6TQcKzV3rXznXIOM0kd4Ecrwx54FvgfsVbCnPKRDQ69qpDtTg%2BIlfbubHo%2BNvNWf0bnUldS%2Fv06gjEvIrjebVXe1XG8iZPKWzIXR6Guwa7B7KeDX7TyaDB41HFww6asPJpsGqQ%2Fih6Oj1hblAsm4xQ6PPWuTsePvY...p%3A%2F%2Fnextcloud.domain.com%2Fapps%2Fuser_saml%2Fsaml%2Flogin&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=oIB8Z9pQKk5P3gERfxmsOvHUuwi3J9utNA0EgT8Nv09zX2sphpQwcQTbqtfgv%2Fb2n5ngZ1De6A5ySYklo%2FyQ6jqKWeSizbRQzsc23W04gN7kqy5FBh%2Fu%2F%2FMLN6wtcAZBL6x38yJLgH3RNw9PNnxUfepEAj6nYk4A2e0ls22qZJoGkzfkft5CPbIU3QdAKMhsvAejJI1MOKCsedMZ4fxpvkkTFhOw7PF%2Fjwv9h2eZRWtO4EMuo3TvRFb3XY0jJNzIQiNbCVDCziPZryzXPCdvCgOuKn6%2FkapOg96QnZAgsVDI8dFTjE1dz%2FOWYkwaQeJMFvsFhaAs8eqoFeb7bkgbuQ%3D%3D' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://nextcloud.domain.com/apps/user_saml/saml/acs'. This endpoint should be made available over a secure connection.
saml?SAMLRequest=lZJfT2IxEMXf%2BRSm79D7B7luAyQoq5IgEGF98MX09g5LY2977bSI395yu%2B6qyZo4bzOd88uZkw6R16phE%2B92%2BhaePKDrnIQ61Eojax9HxFvNDEeJTPMakDnB1pObOct6CWuscUYYRT7JvlZxRLBOGh1ls%2BmILBc%2F58ur2eJhm50NgBdC5GWa5Tzb5iWc5v1iMDg7LfJSFMWPfgllEqV3YDFwRiRgSSfSED3MNDquXZgnWdJN0m462KQZyzPW799H6TQcKzV3rXznXIOM0kd4Ecrwx54FvgfsVbCnPKRDQ69qpDtTg%2BIlfbubHo%2BNvNWf0bnUldS%2Fv06gjEvIrjebVXe1XG8iZPKWzIXR6Guwa7B7KeDX7TyaDB41HFww6asPJpsGqQ%2Fih6Oj1hblAsm4xQ6PPWuTsePvYmpwvOKOD%2Bl7yj9uwxbhvtl0ZZQUL%2B38WJfG1tz9P4a0l7YTWXW37SrzGhsQciuhIn8xE6XM80Ww6GBEnPVATui404lmPn7d8Ss%3D&RelayState=http%3A%2F%2Fnextcloud.domain.com%2Fapps%2Fuser_saml%2Fsaml%2Flogin&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=oIB8Z9pQKk5P3gERfxmsOvHUuwi3J9utNA0EgT8Nv09zX2sphpQwcQTbqtfgv%2Fb2n5ngZ1De6A5ySYklo%2FyQ6jqKWeSizbRQzsc23W04gN7kqy5FBh%2Fu%2F%2FMLN6wtcAZBL6x38yJLgH3RNw9PNnxUfepEAj6nYk4A2e0ls22qZJoGkzfkft5CPbIU3QdAKMhsvAejJI1MOKCsedMZ4fxpvkkTFhOw7PF%2Fjwv9h2eZRWtO4EMuo3TvRFb3XY0jJNzIQiNbCVDCziPZryzXPCdvCgOuKn6%2FkapOg96QnZAgsVDI8dFTjE1dz%2FOWYkwaQeJMFvsFhaAs8eqoFeb7bkgbuQ%3D%3D:1 Mixed Content: The page at 'https://keycloak.domain.com/auth/realms/homelab/protocol/saml?SAMLRequest=lZJfT2IxEMXf%2BRSm79D7B7luAyQoq5IgEGF98MX09g5LY2977bSI395yu%2B6qyZo4bzOd88uZkw6R16phE%2B92%2BhaePKDrnIQ61Eojax9HxFvNDEeJTPMakDnB1pObOct6CWuscUYYRT7JvlZxRLBOGh1ls%2BmILBc%2F58ur2eJhm50NgBdC5GWa5Tzb5iWc5v1iMDg7LfJSFMWPfgllEqV3YDFwRiRgSSfSED3MNDquXZgnWdJN0m462KQZyzPW799H6TQcKzV3rXznXIOM0kd4Ecrwx54FvgfsVbCnPKRDQ69qpDtTg%2BIlfbubHo%2BNvNWf0bnUldS%2Fv06gjEvIrjebVXe1XG8iZPKWzIXR6Guwa7B7KeDX7TyaDB41HFww6asPJpsGqQ%2Fih6Oj1hblAsm4xQ6PPWuTsePvY...p%3A%2F%2Fnextcloud.domain.com%2Fapps%2Fuser_saml%2Fsaml%2Flogin&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=oIB8Z9pQKk5P3gERfxmsOvHUuwi3J9utNA0EgT8Nv09zX2sphpQwcQTbqtfgv%2Fb2n5ngZ1De6A5ySYklo%2FyQ6jqKWeSizbRQzsc23W04gN7kqy5FBh%2Fu%2F%2FMLN6wtcAZBL6x38yJLgH3RNw9PNnxUfepEAj6nYk4A2e0ls22qZJoGkzfkft5CPbIU3QdAKMhsvAejJI1MOKCsedMZ4fxpvkkTFhOw7PF%2Fjwv9h2eZRWtO4EMuo3TvRFb3XY0jJNzIQiNbCVDCziPZryzXPCdvCgOuKn6%2FkapOg96QnZAgsVDI8dFTjE1dz%2FOWYkwaQeJMFvsFhaAs8eqoFeb7bkgbuQ%3D%3D' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://nextcloud.domain.com/apps/user_saml/saml/acs'. This endpoint should be made available over a secure connection.
onload @ saml?SAMLRequest=lZJfT2IxEMXf%2BRSm79D7B7luAyQoq5IgEGF98MX09g5LY2977bSI395yu%2B6qyZo4bzOd88uZkw6R16phE%2B92%2BhaePKDrnIQ61Eojax9HxFvNDEeJTPMakDnB1pObOct6CWuscUYYRT7JvlZxRLBOGh1ls%2BmILBc%2F58ur2eJhm50NgBdC5GWa5Tzb5iWc5v1iMDg7LfJSFMWPfgllEqV3YDFwRiRgSSfSED3MNDquXZgnWdJN0m462KQZyzPW799H6TQcKzV3rXznXIOM0kd4Ecrwx54FvgfsVbCnPKRDQ69qpDtTg%2BIlfbubHo%2BNvNWf0bnUldS%2Fv06gjEvIrjebVXe1XG8iZPKWzIXR6Guwa7B7KeDX7TyaDB41HFww6asPJpsGqQ%2Fih6Oj1hblAsm4xQ6PPWuTsePvYmpwvOKOD%2Bl7yj9uwxbhvtl0ZZQUL%2B38WJfG1tz9P4a0l7YTWXW37SrzGhsQciuhIn8xE6XM80Ww6GBEnPVATui404lmPn7d8Ss%3D&RelayState=http%3A%2F%2Fnextcloud.domain.com%2Fapps%2Fuser_saml%2Fsaml%2Flogin&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=oIB8Z9pQKk5P3gERfxmsOvHUuwi3J9utNA0EgT8Nv09zX2sphpQwcQTbqtfgv%2Fb2n5ngZ1De6A5ySYklo%2FyQ6jqKWeSizbRQzsc23W04gN7kqy5FBh%2Fu%2F%2FMLN6wtcAZBL6x38yJLgH3RNw9PNnxUfepEAj6nYk4A2e0ls22qZJoGkzfkft5CPbIU3QdAKMhsvAejJI1MOKCsedMZ4fxpvkkTFhOw7PF%2Fjwv9h2eZRWtO4EMuo3TvRFb3XY0jJNzIQiNbCVDCziPZryzXPCdvCgOuKn6%2FkapOg96QnZAgsVDI8dFTjE1dz%2FOWYkwaQeJMFvsFhaAs8eqoFeb7bkgbuQ%3D%3D:1
saml?SAMLRequest=lZJfT2IxEMXf%2BRSm79D7B7luAyQoq5IgEGF98MX09g5LY2977bSI395yu%2B6qyZo4bzOd88uZkw6R16phE%2B92%2BhaePKDrnIQ61Eojax9HxFvNDEeJTPMakDnB1pObOct6CWuscUYYRT7JvlZxRLBOGh1ls%2BmILBc%2F58ur2eJhm50NgBdC5GWa5Tzb5iWc5v1iMDg7LfJSFMWPfgllEqV3YDFwRiRgSSfSED3MNDquXZgnWdJN0m462KQZyzPW799H6TQcKzV3rXznXIOM0kd4Ecrwx54FvgfsVbCnPKRDQ69qpDtTg%2BIlfbubHo%2BNvNWf0bnUldS%2Fv06gjEvIrjebVXe1XG8iZPKWzIXR6Guwa7B7KeDX7TyaDB41HFww6asPJpsGqQ%2Fih6Oj1hblAsm4xQ6PPWuTsePvYmpwvOKOD%2Bl7yj9uwxbhvtl0ZZQUL%2B38WJfG1tz9P4a0l7YTWXW37SrzGhsQciuhIn8xE6XM80Ww6GBEnPVATui404lmPn7d8Ss%3D&RelayState=http%3A%2F%2Fnextcloud.domain.com%2Fapps%2Fuser_saml%2Fsaml%2Flogin&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=oIB8Z9pQKk5P3gERfxmsOvHUuwi3J9utNA0EgT8Nv09zX2sphpQwcQTbqtfgv%2Fb2n5ngZ1De6A5ySYklo%2FyQ6jqKWeSizbRQzsc23W04gN7kqy5FBh%2Fu%2F%2FMLN6wtcAZBL6x38yJLgH3RNw9PNnxUfepEAj6nYk4A2e0ls22qZJoGkzfkft5CPbIU3QdAKMhsvAejJI1MOKCsedMZ4fxpvkkTFhOw7PF%2Fjwv9h2eZRWtO4EMuo3TvRFb3XY0jJNzIQiNbCVDCziPZryzXPCdvCgOuKn6%2FkapOg96QnZAgsVDI8dFTjE1dz%2FOWYkwaQeJMFvsFhaAs8eqoFeb7bkgbuQ%3D%3D:1 GET https://nextcloud.domain.com/apps/user_saml/saml/acs 405
onload @ saml?SAMLRequest=lZJfT2IxEMXf%2BRSm79D7B7luAyQoq5IgEGF98MX09g5LY2977bSI395yu%2B6qyZo4bzOd88uZkw6R16phE%2B92%2BhaePKDrnIQ61Eojax9HxFvNDEeJTPMakDnB1pObOct6CWuscUYYRT7JvlZxRLBOGh1ls%2BmILBc%2F58ur2eJhm50NgBdC5GWa5Tzb5iWc5v1iMDg7LfJSFMWPfgllEqV3YDFwRiRgSSfSED3MNDquXZgnWdJN0m462KQZyzPW799H6TQcKzV3rXznXIOM0kd4Ecrwx54FvgfsVbCnPKRDQ69qpDtTg%2BIlfbubHo%2BNvNWf0bnUldS%2Fv06gjEvIrjebVXe1XG8iZPKWzIXR6Guwa7B7KeDX7TyaDB41HFww6asPJpsGqQ%2Fih6Oj1hblAsm4xQ6PPWuTsePvYmpwvOKOD%2Bl7yj9uwxbhvtl0ZZQUL%2B38WJfG1tz9P4a0l7YTWXW37SrzGhsQciuhIn8xE6XM80Ww6GBEnPVATui404lmPn7d8Ss%3D&RelayState=http%3A%2F%2Fnextcloud.domain.com%2Fapps%2Fuser_saml%2Fsaml%2Flogin&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=oIB8Z9pQKk5P3gERfxmsOvHUuwi3J9utNA0EgT8Nv09zX2sphpQwcQTbqtfgv%2Fb2n5ngZ1De6A5ySYklo%2FyQ6jqKWeSizbRQzsc23W04gN7kqy5FBh%2Fu%2F%2FMLN6wtcAZBL6x38yJLgH3RNw9PNnxUfepEAj6nYk4A2e0ls22qZJoGkzfkft5CPbIU3QdAKMhsvAejJI1MOKCsedMZ4fxpvkkTFhOw7PF%2Fjwv9h2eZRWtO4EMuo3TvRFb3XY0jJNzIQiNbCVDCziPZryzXPCdvCgOuKn6%2FkapOg96QnZAgsVDI8dFTjE1dz%2FOWYkwaQeJMFvsFhaAs8eqoFeb7bkgbuQ%3D%3D:1
Navigated to https://nextcloud.domain.com/apps/user_saml/saml/acs
Navigated to chrome-error://chromewebdata/
</details>

**Comment by reavessm** [comment]
Upate: As soon as I submitted this bug, the SSO & SAML app had an update to 2.5.0.  I still experienced these issues after updating.

**Comment by reavessm** [comment]
Any update on this?

**Comment by Sx3** [comment]
Same Issue here...@reavessm did u solved it ?

**Comment by reavessm** [comment]
Still having this issue, before and after upgrading to 19.0.2

**Comment by rgrosjean** [comment]
Same issue for us. We were first using NC 19.0.0 running in Docker it was working fine but after upgrading to 19.0.1, 19.0.2 or even 19.0.3-rc, the redirection stopped to work on Chrome. On Firefox, it is still working fine.
Our installation is very simple since we were only testing the possibility of integrating Keycloak as IdP.
The only App that we added is the "SAML & SSO Authentication"

**Comment by lokeshkumarprakashkumar** [comment]
We are facing the same issue as @rgrosjean wrote. It works fine on Firefox not in chrome.

**Comment by reavessm** [comment]
FWIW, NC 20.0.1 seems to break Firefox as well.  Now both are returning 405, but the firefox one just shows a white screen.  I have to check the nextcloud docker logs to see the 405

**Comment by reavessm** [comment]
Any thoughts @LukasReschke ?

**Comment by pierreozoux** [comment]
We had the same issue with 18.0.9, updated to 18.0.12, and the issue is resolved :)

Thanks a lot :)

Feel free to reopen otherwise.
