### ISSUE TITLE
Skeleton files are not copied over after first login

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/user_saml#393]
For users that login via SAML ( LDAP BACKEND) the skeleton files are not copied over
Still present after #220 

### Steps to reproduce
1. Install nextcloud, configure ldap module, and configure user_saml module with $REMOVE_USER variable
2. Login for the first time with some user in LDAP

### Expected behaviour
The skeleton files should be copied to the user files directory.

### Actual behaviour
No files are copied. 

### Server configuration
Nextcloud 18.0.0
CentOS-8

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/user_saml/pull/797
