### ISSUE TITLE
Filter specific groups from SAML provider

### ISSUE THREAD

**Issue by jecal22** [nextcloud/user_saml#402]
This is not really an issue but a feature request, unless there is already a capability for this and I have just not found it yet.

First, I should mention that I am using AzureAD integrated via SAML with Nextcloud.

I have been able to get the SSO & SAML authentication app to successfully pull all groups that a user is a member of by using the Group Claim on the AzureAD side and add them to Nextcloud, and the user is correctly added into each group properly.  

However, I have a lot of groups in my AzureAD environment, 99% of which are unnecessary in Nextcloud and just results in a messy Group list display a well as when viewing the User List, which shows every group, so one user takes up half of the screen due to extensive group memberships.

What I would like to be able to do is specify a specific list of Groups that should be imported during the SAML authentication process so that only those that I configure will actually be added and all others provided by AzureAD are simply ignored.

I have not found any way of doing this in the SSO & SAML authentication app configuration or on the Azure AD side.  The Group Claim simply provides a list of all groups the user is a member of, and Nextcloud automatically adds every one of them.

**Comment by auri3s** [comment]
Hi @jecal22,
I have a similar topic but we do not use AzureAD but the ADFS.
I am still at that point to make the group sync work.
My issue is that nextcloud throws the error "SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'gid' at row 1" because there are to many groups.
Did you have this issue as well?

Best regards
auri3s

**Comment by blizzz** [comment]
It's rather the task in the SP configuration to send only the required groups from the IdP to the client. Everything else is leaking group information… So, while technically it is possible to add this feature, Nextcloud is the wrong place to configure group filtering.
