### ISSUE TITLE
Allow setting of "retrieveParametersFromServer"

### ISSUE THREAD

**Issue by Quebrantos** [nextcloud/user_saml#403]
I have been setting up a SSO/SLO environment with other applications (WordPress, and Microsoft OWA) using Microsoft ADFS as iDP . I had a weird issue when logged in into more than one application (NextCloud included) and initiating the logout from one of the other applications. NextCloud SLO proccess broke the chain of SAML Logout Requests/Responses not finishing its' own logout and not allowing the iDP to logout the rest of applications.

I have been able to fix the issue editing the file /apps/user_saml/lib/Controller/SAMLController.php and setting requestParametersFromServer to true in the porcessSLO call at line 354
[...]
                                $targetUrl = $auth->processSLO($keepLocalSession, null, **true**, null, $stay);
[...]

https://github.com/onelogin/php-saml/issues/130

**Comment by LukasReschke** [comment]
Asked in https://github.com/onelogin/php-saml/issues/466 if we can remove this setting completely.
