### ISSUE TITLE
User uid does not match as it is interpreted case sensistive

### ISSUE THREAD

**Issue by mpibpc-mroose** [nextcloud/user_saml#406]
Given I have my NextCloud configured with LDAP Authentication and want to provide additional SAML authentication provided by KeyCloak.  In the default configuration LDAP usese the objectGUID of LDAP as username and stores it uppercase.

KeyCloak on the other side stores that ID in lower case and there seems to be no possibility to deliver that as upper case SAML attribute.

So there is no possibility "to match" users from LDAP and SAML:

![image](https://user-images.githubusercontent.com/8191021/75971378-ff24d080-5ed1-11ea-9770-2ffd3b72c904.png)

Is there any possibility to make the UID matching case insensitive?

**Comment by blizzz** [comment]
user IDs are case sensitive in Nextcloud. The SP config has to ensure the matching value is being passed to Nextcloud.

**Comment by tgurr** [comment]
@mpibpc-mroose Have you ever been able to find a solution for that? I'm running into the same issue when trying to use Keycloak in combination with Active Directory. No matter what I have no attribute not running into the problem with, nothing works due to Nextcloud being case sensitive, UUID, sAMAccountName, userPrincipalName, mail, ...

**Comment by cluck** [comment]
Not exactly pertinent to OP's issue, as he's looking to use an an IdP
if you're using user_saml to enable Kerberos/NEGOTIATE login (instead of Keycloak), you may find yourself able to convert the uniqueID to uppercase using ProxyFCGISetEnvIf:

```
<Location "/apps/user_saml/saml/login">
    <IfModule mod_auth_gssapi.c>
       LookupUserAttr uniqueID REMOTE_USER_USERID " "
   </IfModule>
</Location>
ProxyFCGISetEnvIf "toupper(reqenv('REDIRECT_REMOTE_USER_USERID')) =~ m|(.+)|" REDIRECT_REMOTE_USER_USERID_UCASE "$1"
```
You'll need to use REDIRECT_REMOTE_USER_USERID_UCASE as "uid" in user_saml in Nextcloud.

**Comment by cluck** [comment]
Not exactly pertinent to OP's issue, but sharing the same root limitation: if you're using user_saml to enable Kerberos/NEGOTIATE login, you may find yourself in the position that Nextcloud derives uppercase user_ids from LDAP objectGUID, while the uniqueID retrieved from SSSD via Apache's LookupUserAttr is lowercase.

You'll be able to convert the lowercase uniqueID to uppercase using ProxyFCGISetEnvIf:

```
<Location "/apps/user_saml/saml/login">
    <IfModule mod_auth_gssapi.c>
       LookupUserAttr uniqueID REMOTE_USER_USERID " "
   </IfModule>
</Location>
ProxyFCGISetEnvIf "toupper(reqenv('REDIRECT_REMOTE_USER_USERID')) =~ m|(.+)|" REDIRECT_REMOTE_USER_USERID_UCASE "$1"
```
Then you'll need to point user_saml to read REDIRECT_REMOTE_USER_USERID_UCASE as "uid".

Maybe the same can be used to work around https://github.com/nextcloud/server/issues/44486

**Comment by Kurg4ch** [comment]
Hello everyone, has anyone found a solution to this problem?

**Comment by tgurr** [comment]
> Hello everyone, has anyone found a solution to this problem?

@Kurg4ch Not a solution but a workaround implemented on the Keycloak side via JavaScript to transform the lowercase item (LDAP_ID/UUID in this case) to uppercase to allow things to match, see https://github.com/keycloak/keycloak/issues/15312 for details. Still having to live with this hack to this date.

**Comment by scimitar4444** [comment]
@tgurr. Is Javascript still running under 26.1.3?
I can't get it to run..

**Comment by tgurr** [comment]
> [@tgurr](https://github.com/tgurr). Is Javascript still running under 26.1.3? I can't get it to run..

You've to enable the `scripts` feature as described at https://www.keycloak.org/server/features there are various ways to do this either by command line, config or by environment variabled as described at https://www.keycloak.org/server/configuration#_formats_for_configuration e.g. `KC_FEATURES="scripts"` is what I personally use these days referenced via a systemd service file (citing only the relevant part):

```
[Service]
EnvironmentFile=-/etc/default/keycloak
```
