### ISSUE TITLE
Kerberos: every time a new apptoken

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/user_saml#411]
- enable user_saml app
- use UserPrincipalName as environment variable
- add SetEnv UserPrincipalName "Johnson" to apache virtualhost config
- do a curl 
```
curl --request PROPFIND \
  --url http://localhost/nc/remote.php/dav/files/Johnson/ \
  --header 'accept-encoding: gzip' \
  --header 'content-type: application/xml' \
  --header 'depth: 2' \
  --data '<?xml version="1.0" encoding="UTF-8"?>
<D:propfind xmlns:D="DAV:">
<D:prop>
<D:displayname/>
<D:resourcetype/>
<favorite xmlns="http://owncloud.org/ns"/>
<is-encrypted xmlns="http://nextcloud.org/ns"/>
<mount-type xmlns="http://nextcloud.org/ns"/>
<D:creationdate/>
<id xmlns="http://owncloud.org/ns"/>
<D:getetag/>
<permissions xmlns="http://owncloud.org/ns"/>
<share-types xmlns="http://owncloud.org/ns"/>
<share-expiration xmlns="http://nextcloud.org/ns"/>
<rich-workspace xmlns="http://nextcloud.org/ns"/>
<owner-id xmlns="http://owncloud.org/ns"/>
	<X-Hash-MD5 xmlns="http://nextcloud.org/ns"/>
	<D:quota-used-bytes/>
<D:getcontenttype/>
<sharees  xmlns="http://nextcloud.org/ns"/>
</D:prop></D:propfind>
```
- see in settings -> security for every request a new apptoken

@rullzer maybe you have an idea? :heart:

**Comment by rullzer** [comment]
How are you authenticating? Because if it is basic Auth this is expected.

**Comment by rullzer** [comment]
Ah stupid kerberos.
So yeah not much we can do. If you don't reuse the session or use an Auth token we create one on each request.

**Comment by tobiasKaminsky** [comment]
On my test setup it is working, but on a real life setting it is thowing a bunch of 403 when iOS is trying to target getapppassword endpoint.
That was the reason I tested this and then found out about this multiple apptokens…

**Comment by rullzer** [comment]
Get me access ot that and we can debug it ;)

**Comment by tobiasKaminsky** [comment]
Ok, seems that I mixed up sessions and app token in security view.
Indeed it is only one one auth token, but multiple sessions, which then are cleaned up.
