### ISSUE TITLE
[Feature] Configure SAML using config.php

### ISSUE THREAD

**Issue by Zocker1999NET** [nextcloud/user_saml#421]
Currently this app can only be configured by hand due to the configuration using the UI which is, in general, not bad. But I think most system administrators would more like to configure SAML using the `config.php`, because this would enable configuring SAML in Nextcloud fully automatic using configuration management tools like Ansible, Puppet or others. Even if the configuration is done by hand, this approach can still save time because you can copy the configuration as plain text and replace hostnames and certificates instead of looking up how the attributes are mapped for example.

**Comment by blizzz** [comment]
no, app config won't go into config.php

you can already use occ config:app:… to modify configurations
