### ISSUE TITLE
SAML stops working after upgrade to NC 19.

### ISSUE THREAD

**Issue by cloud-rocket** [nextcloud/user_saml#433]
SAML is no longer working after upgrade to NC 19. Empty page with `Null` is displayed after login succeeds through Google G. Suite.

Commenting out the following code solves the problem as long as multiple IDPs are not configured in NextCloud (when more than 1 IDP is configured - the plugin doesn't know which one to use as $idp is empty):
```
//if(is_null($AuthNRequestID) || $AuthNRequestID === '' || is_null($idp)) {
//	return;
//}
```

I was digging through the code and discovered that values in the Session are not preserved - both `user_saml.AuthNRequestID` and `user_saml.Idp` are empty when `assertionConsumerService` is called. They were initialized properly during `login($idp)` call.

* Why should `AuthNRequestID` be stored in the Session in the first place, as SAML protocol POST to ACP call is providing this value. Using the value from SAML POST call would also solve [this](https://github.com/nextcloud/user_saml/issues/208) problem altogether.
* The problem also referenced [here](https://help.nextcloud.com/t/idp-iniatied-saml-logging-null-webpage-text-while-sp-initiated-works-fine/68116/9) 

### Server configuration

**Operating system**: GCP Container OS with docker-compose based setup
**Web server:** Nginx reverse proxy
**Database:** MySQL
**PHP version:**
**Nextcloud version:** 19.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 18.0.5

**Comment by blizzz** [comment]
Pendant in server is https://github.com/nextcloud/server/issues/21474, fix in #430 in combination with https://github.com/nextcloud/server/pull/21479, so 19.0.1 will be needed.
