### ISSUE TITLE
Use php-saml >= 2.10.0

### ISSUE THREAD

**Issue by pitbulk** [nextcloud/user_saml#44]
Hi, nice to see you are using my toolkit to add SAML support to nextcloud

please, require the [php-saml 2.10.0](https://github.com/onelogin/php-saml/releases/tag/v2.10.0) version.
It includes a security patch that contains extra validations that will prevent signature wrapping attacks and other security improvements.Previous versions are vulnerable.

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by LukasReschke** [comment]
Thanks, @pitbulk. We'll change this for our next minor and major releases. Much appreciated.
