### ISSUE TITLE
IDP-initiated SLO gives me an CSRF check failed

### ISSUE THREAD

**Issue by ebogaard** [nextcloud/user_saml#45]
When using IDP-initiated Single Log Off (SLO) to logout of Nextcloud, I get the following message on screen:

```
Access forbidden
CSRF check failed
```

That seems fine and secure, but I expected to find an option to trust a certain list of domains.
The Nextcloud session isn't invalidated at this point, by the way.

**Further info**

1. The actual SLO-request is sent to "https://test-domain/apps/user_saml/saml/sls?SAMLRequest=xxx"
2. The response I get back is "412 Precondition failed"

Is this enough for you to get an idea what's happening, or do you need more?
I'm happy to help, so please ask.

**Comment by LukasReschke** [comment]
That's interesting. That should actually work quite fine. I do have a suspicion there though. Let's see if it is that :)

Can you inspect the URL that is used for the logout request? To do that inspect the source and I'd need the href that is used on the logout button.

**Comment by ebogaard** [comment]
When clicking on the idp logout-button (so not the logout-button in Nextcloud, but on a separate page that uses the IDP's api), the following requests take place:

* Click button: https://dev-login.domain/index.php?action=logout
* https://dev-login.domain/saml/saml2/idp/SingleLogoutService.php?SAMLRequest=xxx
* https://dev-login.domain/saml/module.php/core/idp/resumelogout.php?id=xxx
* https://test-nc.domain/apps/user_saml/saml/sls?SAMLRequest=xxx

dev-login.domain = IDP ( = newest SimpleSamlPHP)
test-nc.domain = Nectcloud

**Comment by KamilWo** [comment]
As temporary fix I am using `@NoCSRFRequired`
```
	/**
	 * @NoAdminRequired
         * @NoCSRFRequired
	 */
	public function singleLogoutService() {
```
in `user_saml/lib/Controller/SAMLController.php`.

**Comment by fri-sch** [comment]
This seems to be a duplicate of #161

**Comment by DylannCordel** [comment]
I confirm. It's a duplicated and it's now merged in master (thx @skjnldsv )

**Comment by skjnldsv** [comment]
duplicate of #161
