### ISSUE TITLE
Cannot pass the attribute information from SP to NextCloud (??

### ISSUE THREAD

**Issue by RyzeVia** [nextcloud/user_saml#454]
### Steps to reproduce
1. installed Shibboleth SP and configured it
2. registered our SP's metadata to IdP in our organization (Shibboleth IDP)
3. deployed NextCloud version 19 and installed user_saml application
4. check local login to NextCloud -> OK
5. set IdP Entity ID and SAML2.0 Endpoint such as
     https://(--sp's address--)/Shibboleth.sso/Login?entityID=(--Idp Entity ID--)&target=(--nextcloud url--)
6.  Attribute for UID is set as "eppn"
7. set X.509 cert for IdP
8. login to nextcloud with SSO 

We also check following:
- set true for showAttributeValues on shibboleth2.xml and accessed to Shibboleth.sso/Session -> Attributes (eppn, displayName and mail) are in.
- after push SSO button on Log-in page, SP's ACS was called and set some cookie. And on calling "user_saml/saml/selectUserBackEnd?redirectUrl=", some cookie is in this calling such as oc_sessionPassphrase, _shibsession_XX, saml_data.

### Expected behaviour
NextCloud make a new account from Shibboleth's Attribute Value
I log in with the account.

### Actual behaviour
NextCloud turn back to log-in page which has two buttons (for Local login & SSO Login )

### Server configuration

**Operating system**:
CentOS 7.8
**Web server:**
Apache 2.4.6-93.el7.centos
**Database:**
MariaDB and SQLite ( Both db we tried. )
**PHP version:**
PHP 7.3.21
**Nextcloud version:** (see Nextcloud admin page)
19.0.1
**Where did you install Nextcloud from:**
Official site by zip format.

**List of activated apps:**
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 7.0.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.3
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.3
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.0
  - user_saml: 3.2.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - encryption
  - groupquota

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXX.XXX.XXX.XXX"
        ],
        "overwritehost": "xxx.xxx.xx",
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "19.0.1.1",
        "overwrite.cli.url": "https:\/\/xxx.xxx.xxx.xxx\/nextcloud",
        "installed": true,
        "debug": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "log_type": "file",
        "logfile": "\/var\/www\/html\/nextcloud\/data\/nextcloud.log",
        "loglevel": "1",
        "maintenance": false
    }
}

### Client configuration
Firefox 80.0.1

**Operating system:**
Windows 10

#### Nextcloud log (data/owncloud.log)
Both nextcloud.log and audit.log have no log on login-flow

#### Browser log
SAML Tracker for Firefox

GET https://(--nextcloud URL--)/index.php/apps/user_saml/saml/login?requesttoken=XXXXXXXXX&originalUrl=&idp=1
GET https://(--SP URL--)/Shibboleth.sso/Login?entityID=(--IDP EntityID--)&target=(--nextcloud url--)&SAMLRequest(--XXX--)&RelayState=(--nextcloud url--)%2Findex.php%2Fapps%2Fuser_saml%2Fsaml%2Flogin&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=(--XXX--)
GET https://(--Idp URL--)/idp/profile/SAML2/Redirect/SSO?SAMLRequest=(--XXX--)&RelayState=ss%3Amem%3A(--XXX--)
GET https://(--Idp URL--)/idp/profile/SAML2/Redirect/SSO?execution=e2s1
--- omit ---
POST https://(--Idp URL--)/idp/profile/SAML2/Redirect/SSO?execution=e2s1
POST https://(--SP URL--)/Shibboleth.sso/SAML2/POST
GET https://(--nextcloud URL--)/
GET https://(--nextcloud URL--)/index.php
GET https://(--nextcloud URL--)/index.php/login
GET https://(--nextcloud URL--)/index.php/apps/user_saml/saml/selectUserBackEnd?redirectUrl=

**Comment by Ornias1993** [comment]
Afaik nextcloud functions as its own SP, why are you trying to create somesort of SP cascade?

**Comment by RyzeVia** [comment]
Thanks Ornias, we misunderstood about user_saml. We'll try it.
