### ISSUE TITLE
SSO to Azure not working due to wrong reply url

### ISSUE THREAD

**Issue by Dezeptor** [nextcloud/user_saml#457]
### Steps to reproduce
1. Set up using this guide: https://medium.com/@ntrussell/enable-nextcloud-sso-authentication-through-microsoft-azure-active-directory-saml-abe37d735cd

### Expected behaviour
login success

### Actual behaviour
Getting this error:
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'http://Nextcloud.company.com/apps/user_saml/saml/metadata'.

Assuming the cause is the replyurl in the metadata file is HTTP an Azure is only accepting HTTPS

### Server configuration

**Operating system**:
Ubuntu server 18 LTS

**Web server:**
DOCKER Container

**Database:**
SQL lite

**PHP version:**
DOCKER Container

**Nextcloud version:** (see Nextcloud admin page)
19.0.3

**Where did you install Nextcloud from:**
Dockerhub

**List of activated apps:**
Default apps + SSO & SAML authentication

**Nextcloud configuration:**

<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => REMOVED,
  'passwordsalt' => REMOVED,
  'secret' => REMOVED,
  'trusted_domains' => 
  array (
    0 => REMOVED,
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'sqlite3',
  'version' => '19.0.3.1',
  'overwrite.cli.url' => 'https://REMOVED',
  'installed' => true,
  'mail_smtpmode' => REMOVED,
  'mail_smtpsecure' => REMOVED,
  'mail_sendmailmode' => REMOVED,
  'mail_smtphost' => REMOVED,
  'mail_smtpport' => REMOVED,
  'mail_from_address' => REMOVED,
  'mail_domain' => REMOVED,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => REMOVED,
  'mail_smtppassword' => REMOVED,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'updater.secret' => REMOVED,
);
```

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

### Logs

#### Nextcloud log (data/owncloud.log)
no log?

#### Browser log
No log?

**Comment by semyonsh** [comment]
Bit late to the party but this has to do with your NC config returning **http** instead of **https**. 

Adding the following into config/config.php did it for me: 
`
  'overwriteprotocol' => 'https',`

You can verify by downloading the metadata xml from the Nextcloud SAML config, the reply urls should've changed to https. 

Source: https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html#overwrite-parameters
