### ISSUE TITLE
SAML Support for Mobile Clients (iOS/Android)

### ISSUE THREAD

**Issue by SalimHaddou** [nextcloud/user_saml#48]
Hi,

I have a working SAML implementation between my IdP and Nextcloud.
Is there any way to support SAML authentication for iOS and Android client apps ?

Thanks.
Salim

**Comment by akuckartz** [comment]
:+1:

**Comment by SalimHaddou** [comment]
Is there a workaround with the current version (10.0.1) using app passwords ? (I couldn't get that to work).

**Comment by MariusBluem** [comment]
Have you tried to create a new app-password in the user-settings to use it in the clients - and this did not work? @SalimHaddou

**Comment by LukasReschke** [comment]
> Have you tried to create a new app-password in the user-settings to use it in the clients - and this did not work? @SalimHaddou

That's the current workaround yes. In the long-term we should move to an authentication style that makes it possible for our native clients to login using SAML or any other auth type as well. But that's mid- to long-term :-)

**Comment by SalimHaddou** [comment]
Yes, this is what I have tried.
I am using the Android Nextcloud App.
This is what I am seeing in the server logs (obfuscated):
{"reqId":"***************","remoteAddr":"***********","app":"core","message":"Login failed: '<username>' (Remote IP: '********')","level":2,"time":"2016-11-13T19:44:17+00:00","method":"HEAD","url":"\/remote.php\/webdav\/","user":"--"}

This is what I captured on my reverse proxy on the way:

<HTTP_REQUEST>: HEAD /remote.php/webdav/ 1.1
<HTTP_REQUEST>: name: Authorization : Basic (b64encode(username:AAAA-BBBB-CCCC-DDDD))
<HTTP_REQUEST>: name: User-Agent : Mozilla/5.0 (Android) ownCloud-android/1.3.1
<HTTP_REQUEST>: name: Host : (obfuscated)

Is that normal it's just doing HEAD on the webdav URI ?

**Comment by SalimHaddou** [comment]
@LukasReschke @MariusBluem Any ideas what I am doing wrong with App Password ?

**Comment by LukasReschke** [comment]
@SalimHaddou Can you provide the server configuration section from https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md? That may shed some more light on it.

**Comment by SalimHaddou** [comment]
@LukasReschke Here you go:

### Server configuration
**Operating system**:
FreeNAS 9.10 (FreeBSD 10.3-STABLE)
Nextcloud running in a jail

**Web server:**
Apache/2.4.10 (FreeBSD) OpenSSL/0.9.8zd-freebsd PHP/5.5.16

**Database:**
Mysql Server version: 5.5.39 Source distribution

**PHP version:**
PHP 5.5.16 (cli) (built: Oct 31 2016 02:41:43)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
10.0.1 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
FreeNAS plugin : https://download.freenas.org/plugins/9/x64/

**Signing status:**
<details>
<summary>Signing status</summary>
???

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here:
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_saml: 1.2.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
```
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'htaccess.RewriteBase' => '/',
  'instanceid' => '***************************',
  'passwordsalt' => '*********************************',
  'secret' => '************************************',
  'trusted_domains' =>
  array (
    0 => '<obfuscated>',
  ),
  'datadirectory' => '/media/Cloud',
  'overwrite.cli.url' => 'https://<obfuscated>',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:/tmp/mysql.sock',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '*******************',
  'dbpassword' => '**********************',
  'logtimezone' => 'UTC',
  'installed' => true,
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
my datadirectory /media/Cloud is on a local dataset from a zfs pool

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
SAML IdP (F5 BIG-IP APM 12.1.1 HF2) with Active Directory

**Comment by SalimHaddou** [comment]
**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_saml: 1.2.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
```
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'htaccess.RewriteBase' => '/',
  'instanceid' => '***************************',
  'passwordsalt' => '*********************************',
  'secret' => '************************************',
  'trusted_domains' =>
  array (
    0 => '<obfuscated>',
  ),
  'datadirectory' => '/media/Cloud',
  'overwrite.cli.url' => 'https://<obfuscated>',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:/tmp/mysql.sock',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '*******************',
  'dbpassword' => '**********************',
  'logtimezone' => 'UTC',
  'installed' => true,
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
my datadirectory /media/Cloud is on a local dataset from a zfs pool

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
SAML IdP (F5 BIG-IP APM 12.1.1 HF2) with Active Directory

**Comment by SalimHaddou** [comment]
@LukasReschke @MariusBluem Any leads ?

**Comment by karankotz** [comment]
@LukasReschke Do you have any update on this ? Can we carry on the authentication via an external client with the external IDP(I am using Keycloak) and upload/download files from the nextcloud resource server ?

**Comment by pierreozoux** [comment]
The solution should be to use an app password.
