### ISSUE TITLE
UID mapping not working properly

### ISSUE THREAD

**Issue by andyboeh** [nextcloud/user_saml#504]
### Steps to reproduce
1. Enable SAML SSO and attribute UID mapping, use "email" as UID
2. Login

### Expected behaviour

I am logged in with the UID set to my user name.

### Actual behaviour

A new user with the UID "796B776A-2BAB-B79D-289E-CBA5B629E06A" is created instead. I'm not yet sure what it depends on, because I did not observe this behavior on another instance with a very similar configuration. Further, it seems to have surfaced suddenly. A debug log correctly lists the attributes passed to user_saml, I just can't share it due to privacy reasons.

### Server configuration

NC 20.0.5. with user_saml 3.3.3, auto-provisioning of SAML users allowed.

PHP: 7.3.24

### Possible cause

Commit https://github.com/nextcloud/user_saml/commit/9f53230eb6e1c97b006be30fb83fc230b09534eb changed the way `testEncodedObjectGUID` works, the parameter `strict` to `base64_decode` is set to false. I'm not sure how to interpret the description in the PHP manual, but IMHO `base64_decode` will almost never return false if `strict` is also false, because it simply skips characters it can't decode. 
If I change strict from false to true, I can log in: https://github.com/nextcloud/user_saml/blob/b406b6bdfa7515690695be400348161f6fbfd8b5/lib/UserBackend.php#L705

**Comment by ebogaard** [comment]
This issue + fix applies to nextcloud 19.0.5 + user_saml 3.2.2 as well.

**Comment by andyboeh** [comment]
Thanks for confirming this! We also use "email" as uid and we have observed the same behavior, i.e. not all user accounts are affected.

**Comment by tkriener** [comment]
Same issue here with nextcloud 20.0.5 and user_saml 3.3.3.
The hack from andyboeh did it.

We are mapping the email-address in Keycloak to uid in the assertion and use the uid (email) a username in Keycloak.

I was already getting crazy, because some users where able to work and some not. I did not find any obvious differences in the account on keycloak or nextcloud, nor in the assertions.

**Comment by jukkapirinen** [comment]
Same issue with Azure AD, UPN mapped as UID (http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name) and now it is converted to some other ID and creates a new account for some users.

**Comment by blizzz** [comment]
You may want to try https://github.com/nextcloud/user_saml/pull/505/commits/9672ed6ca5cfe7a57e91afeb9cc6eaa4f8d159b9

**Comment by jukkapirinen** [comment]
Thanks https://github.com/nextcloud/user_saml/commit/9672ed6ca5cfe7a57e91afeb9cc6eaa4f8d159b9 fixes it
