### ISSUE TITLE
Provide way to map names to displayName

### ISSUE THREAD

**Issue by alerque** [nextcloud/user_saml#528]
Nextcloud's `displayName` is a single name field. My iDP (Keycloak) provides two keys, `firstName` and `lastName` but not a combined value. This plugin doesn't seem to have any way to take advantage of the data and combine them. I realize a string concatenation is naive, but it's better than not having the surname data show up at all.

If I set the display name mapper to `firstName` I do get the first name data. Interestingly it doesn't error when setting that value to `firstName lastName` and indeed still seems to come up with the first name, but it does not concatenate them.

**Comment by blizzz** [comment]
Keycloak, as any other IdP, should be configurable to provide other values through its SP configuration.

**Comment by alerque** [comment]
Filed upstream issue: [KEYCLOAK-18126](https://issues.redhat.com/browse/KEYCLOAK-18126).
