### ISSUE TITLE
"Uncaught ReferenceError: jstz is not defined" error in browser console

### ISSUE THREAD

**Issue by orandev** [nextcloud/user_saml#543]
### Steps to reproduce
1. Install NC 22.1.1 (still happening with NC 22.2.3)
2. Log in through user_saml app
3. Check browser console

### Expected behaviour
No javascript error in the browser console

### Actual behaviour
This error is displayed in the browser console:
_Uncaught ReferenceError: jstz is not defined_
related to file _/apps/user_saml/js/timezone.js_ , line 30

### Server configuration
**Operating system**: Ubuntu 18

**Web server:** Apache

**PHP version:** 7.4

**Nextcloud version:** 22.1.1

**Where did you install Nextcloud from:** Download of zip file from https://download.nextcloud.com/server/releases

### Client configuration
**Browser:** Firefox 78.13

**Operating system:** Windows 10

#### Browser log
Uncaught ReferenceError: jstz is not defined
    <anonymous> https://server_url/apps/user_saml/js/timezone.js?v=fc1b204a-5:30

I think it is related to that PR which removed jstz:
https://github.com/nextcloud/server/pull/25850

**Comment by ChristophWurst** [comment]
This was deprecated in Nextcloud 18: https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html

This app should ship its own copy.
