### ISSUE TITLE
Can't login Talk when SSO & SAML authentication enabled

### ISSUE THREAD

**Issue by AleksovAnry** [nextcloud/user_saml#544]
NC 22.1.1

Apache configuration:

	<IfModule mod_ssl.c>
	<VirtualHost *:443>

		ServerName cloud.set.local
		ServerAdmin admin@set.local
		DocumentRoot /var/www/html/nextcloud
		SSLEngine on
		SSLOptions +StrictRequire
		SSLCertificateFile /etc/ssl/certs/cloud.set.local-certificate.pem
		SSLCACertificateFile /etc/ssl/certs/ipa-set-local-ca.pem
		SSLCertificateKeyFile /etc/ssl/private/cloud.set.local-privateKey.key

		<Directory /var/www/html/nextcloud/>
			Options +FollowSymlinks
			AllowOverride All
			<IfModule mod_dav.c>
				Dav off
			</IfModule>
			SetEnv HOME /var/www/html/nextcloud
			SetEnv HTTP_HOME /var/www/html/nextcloud
		</Directory>

		<FilesMatch \.php$>
			# 2.4.10+ can proxy to unix socket
			SetHandler "proxy:unix:/run/php/php7.3-fpm.sock|fcgi://localhost"
		</FilesMatch>

		<IfModule mod_headers.c>
			Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
			Header always set Referrer-Policy "strict-origin-when-cross-origin"
			Header always set X-Content-Type-Options "nosniff"
			Header always set X-Frame-Options "SAMEORIGIN"
		</IfModule>

		<Location /apps/user_saml/saml/login>
			AuthType Kerberos
			AuthName "Kerberos Login"
			KrbMethodNegotiate On
			KrbMethodK5Passwd Off
			KrbAuthRealms SET.LOCAL
			Krb5KeyTab /etc/apache2/http.keytab
			KrbServiceName HTTP/cloud.set.local@SET.LOCAL
			KrbSaveCredentials On
			KrbLocalUserMapping On
			KrbAuthoritative Off
			Require valid-user
			ErrorDocument 401 '<html><meta http-equiv="refresh" content="0; URL=/login?direct=1"><body>SSO did not pass.</body></html>'
		</Location>

		<Location /apps/user_saml/saml/sls>
			Redirect "/" "/login"
		</Location>

		LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" vhost_combined
		LogFormat "%v %h %l %u %t \"%r\" %>s %b" vhost_common
		CustomLog ${APACHE_LOG_DIR}/access.log combined
		ErrorLog ${APACHE_LOG_DIR}/error.log
	</VirtualHost>

	SSLProtocol -all +TLSv1.3 +TLSv1.2
	SSLCipherSuite TLS-CHACHA20-POLY1305-SHA256:TLS-AES-256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384
	SSLHonorCipherOrder on
	SSLCompression off
	SSLSessionTickets off
	SSLUseStapling off
	SSLStaplingResponderTimeout 5
	SSLStaplingReturnResponderErrors off
	SSLOpenSSLConfCmd Curves X448:secp521r1:secp384r1:prime256v1
	SSLOpenSSLConfCmd ECDHParameters secp384r1
	</IfModule>

I'm use ENV configuration. All works fine, but i can't login Talk app. 

When i'm try to login Talk client (iOS), after i entering login and password, opens NC dashboard and Talk not login. If i disable "SSO & SAML authentication" app, all works fine. I think problem in this row `ErrorDocument 401 '<html><meta http-equiv="refresh" content="0; URL=/login?direct=1"><body>SSO did not pass.</body></html>'`, but if i disable it, i can't login anymore (401)

**Comment by AleksovAnry** [comment]
Desktop & mobile client redirects to NC WEB page too, not logged in.

**Comment by cc-cmarher** [comment]
I have the same problem. After we upgrade to user_saml 5.0.0 our Mobile clients redirects to web page. Not able to Grant permission to the app.

**Comment by Orchal** [comment]
Hi,

We have the same issue. Please note that all android and iOS apps (Talk and sync) will ends to show the web page instead of the app content.

It seems there is an issue with the login flow as the authorization button never appears, whereas it works as intended with an LDAP login for example.

Thank you!

**Comment by cc-cmarher** [comment]
We downgrade user_saml to 4.1.1 y our Docker NC 24.0.0 instalation and it is working again. But this is a desperate workaround solution.

**Comment by cc-cmarher** [comment]
We can not connect the Desktop Client either. Navigator opens but after SAML login redirects to NextCloud default web page and not to the authorization web.

**Comment by Orchal** [comment]
I should mention that we use Apéro CAS and the revert in #614 has no effect.
