### ISSUE TITLE
PHP 8 deprecation error regarding `libxml_disable_entity_loader()` on `onelogin/php-saml` 3rdparty

### ISSUE THREAD

**Issue by joaopalma5** [nextcloud/user_saml#548]
Hello,

I configure the user_saml in docker image nextcloud:21.0.3, and works fine. After upgrade to  docker image nextcloud:22 and 22.1.1 and get this error on login:
"Function libxml_disable_entity_loader() is deprecated at /var/www/html/custom_apps/user_saml/3rdparty/vendor/onelogin/php-saml/src/Saml2/Utils.php#85"

I search for that in code and here: https://github.com/nextcloud/user_saml/blob/master/3rdparty/vendor/onelogin/php-saml/src/Saml2/Utils.php#L85 have `$oldEntityLoader = libxml_disable_entity_loader(true);` and this function is deprecated like this page say: https://php.watch/versions/8.0/libxml_disable_entity_loader-deprecation

I suggest update to:
```
+ if (\PHP_VERSION_ID < 80000) {
+      libxml_disable_entity_loader(true);
+ }
``` 

Thanks for attention!

**Comment by itay-grudev** [comment]
I have a quite similar  issue:

```
"method":"POST",
"url":"/apps/user_saml/saml/acs",
"message":"Function libxml_disable_entity_loader() is deprecated at /var/www/html/custom_apps/user_saml/3rdparty/vendor/onelogin/php-saml/src/Saml2/Utils.php#146"
```

Nextcloud version: `22.1.1`

**Comment by Mte90** [comment]
I can confirm the issue and it is a problem as my hosting provider don't let me switch to a minor version...

**Comment by Mte90** [comment]
when is planned the new release with php 8.0 support?
