### ISSUE TITLE
Blank page after successful return from IdP

### ISSUE THREAD

**Issue by eidota** [nextcloud/user_saml#55]
Hi,

we are trying to move our authentification to SAML Shibboleth. After initial configuration errors we got it nearly working. 

When accessing our nextcloud we get instantly referred to the shibboleth authentification page. We enter the credentials, accept the provided information and get referred back to nextcloud. Only that the resulting page (.../owncloud/index.php/apps/user_saml/saml/acs) is empty. The logs from the IdP show a successful login.

We are on nextcloud 10.0.1 with the current master-version of user_saml to fix the occ-bug.

These are the messages in nextcloud.log when trying to login via saml:

`{"reqId":"WD2GEZm7Tj2wPgYW7VgHEQAAAAI","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' at \/disk1\/webserver\/owncloud\/apps\/user_saml\/3rdparty\/vendor\/onelogin\/php-saml\/extlib\/xmlseclibs\/xmlseclibs.php#88","level":3,"time":"2016-11-29T14:43:46+01:00","method":"POST","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/acs","user":"--"}
{"reqId":"WD2GEZm7Tj2wPgYW7VgHEQAAAAI","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Use of undefined constant MCRYPT_MODE_CBC - assumed 'MCRYPT_MODE_CBC' at \/disk1\/webserver\/owncloud\/apps\/user_saml\/3rdparty\/vendor\/onelogin\/php-saml\/extlib\/xmlseclibs\/xmlseclibs.php#89","level":3,"time":"2016-11-29T14:43:46+01:00","method":"POST","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/acs","user":"--"}
{"reqId":"WD2GEZm7Tj2wPgYW7VgHEQAAAAI","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' at \/disk1\/webserver\/owncloud\/apps\/user_saml\/3rdparty\/vendor\/onelogin\/php-saml\/extlib\/xmlseclibs\/xmlseclibs.php#285","level":3,"time":"2016-11-29T14:43:46+01:00","method":"POST","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/acs","user":"--"}
{"reqId":"WD2GEZm7Tj2wPgYW7VgHEQAAAAI","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Call to undefined function mcrypt_module_open() at \/disk1\/webserver\/owncloud\/apps\/user_saml\/3rdparty\/vendor\/onelogin\/php-saml\/extlib\/xmlseclibs\/xmlseclibs.php#319","level":3,"time":"2016-11-29T14:43:46+01:00","method":"POST","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/acs","user":"--"}

{"reqId":"WD2GoLdcqs3xmGPVdeS8rgAAAAk","remoteAddr":"134.28.202.171","app":"no app in context","message":"CSRF check failed","level":0,"time":"2016-11-29T14:46:08+01:00","method":"HEAD","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/login?requesttoken=JgQ1fmRQBjolCxdTbzAPM2wZTzYnDX10OXsieCgXBCE%3D%3AvPw5S6joGXF75CxV%2Ba5OiFK5R8c%2FeYhSVRqH0pQ5rN8%3D","user":"--"}
{"reqId":"WD2GoFzkVkgq6J2xq2DxngAAAAE","remoteAddr":"134.28.202.171","app":"no app in context","message":"CSRF check failed","level":0,"time":"2016-11-29T14:46:08+01:00","method":"HEAD","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/login?requesttoken=YyY6QEMAPRE4HgYqLToWPxMGGSEUcicXNVsjGToiEzk%3D%3A%2BGYvr6SXPQmbjLAtPvwxyBNOejMHSJeIRASUxAek%2FoQ%3D","user":"--"}
{"reqId":"WD2Hw1W@93-eeRRadIsE0wAAAAY","remoteAddr":"134.28.202.171","app":"no app in context","message":"CSRF check failed","level":0,"time":"2016-11-29T14:50:59+01:00","method":"HEAD","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/login?requesttoken=WBdyDEgVIHoBJXAXFxpdWwwmUS4LTGk3FCMkRg1qI1Q%3D%3A6M0o8wzQIJ2Abl71mv4gZc9twQI2KZBlgc1M8QJfiU4%3D","user":"--"}
{"reqId":"WD2Hw8c4s-T@Syd@O-ag1wAAAAM","remoteAddr":"134.28.202.171","app":"no app in context","message":"CSRF check failed","level":0,"time":"2016-11-29T14:50:59+01:00","method":"HEAD","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/login?requesttoken=UzgpDx8%2BPjoCTg4kb0MEFlMDFQojRAF1OCUDWBkiJAQ%3D%3A5HCbMDhVsyVk5upljwtoKvyMlTLsKNiOxS%2Bw%2BK3CZf8%3D","user":"--"}`

Any idea what could be causing this?

Best regards,

Tim

**Comment by LukasReschke** [comment]
Can you enable debug at https://github.com/nextcloud/user_saml/blob/27c2602298de4236d26cb80ef635ca4511d639cd/lib/samlsettings.php#L46 and see if that gives you any more output?

**Comment by eidota** [comment]
Another try with debug enabled doesnt show more information unfortunately:

`{"reqId":"WD2Ld1zkVkgq6J2xq2DxsAAAAAE","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' at \/disk1\/webserver\/owncloud\/apps\/user_saml\/3rdparty\/vendor\/onelogin\/php-saml\/extlib\/xmlseclibs\/xmlseclibs.php#88","level":3,"time":"2016-11-29T15:06:47+01:00","method":"POST","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/acs","user":"--"}
{"reqId":"WD2Ld1zkVkgq6J2xq2DxsAAAAAE","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Use of undefined constant MCRYPT_MODE_CBC - assumed 'MCRYPT_MODE_CBC' at \/disk1\/webserver\/owncloud\/apps\/user_saml\/3rdparty\/vendor\/onelogin\/php-saml\/extlib\/xmlseclibs\/xmlseclibs.php#89","level":3,"time":"2016-11-29T15:06:47+01:00","method":"POST","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/acs","user":"--"}
{"reqId":"WD2Ld1zkVkgq6J2xq2DxsAAAAAE","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' at \/disk1\/webserver\/owncloud\/apps\/user_saml\/3rdparty\/vendor\/onelogin\/php-saml\/extlib\/xmlseclibs\/xmlseclibs.php#285","level":3,"time":"2016-11-29T15:06:47+01:00","method":"POST","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/acs","user":"--"}
{"reqId":"WD2Ld1zkVkgq6J2xq2DxsAAAAAE","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Call to undefined function mcrypt_module_open() at \/disk1\/webserver\/owncloud\/apps\/user_saml\/3rdparty\/vendor\/onelogin\/php-saml\/extlib\/xmlseclibs\/xmlseclibs.php#319","level":3,"time":"2016-11-29T15:06:47+01:00","method":"POST","url":"\/owncloud\/index.php\/apps\/user_saml\/saml\/acs","user":"--"}`

We are on loglevel "everything" btw.

**Comment by eidota** [comment]
Does the app need php-mcrypt installed? The error messages hint at that.

**Comment by LukasReschke** [comment]
Yes. mcrypt is required. I'll update the app to require it on installation time.

**Comment by dalareo** [comment]
Can mcrypt be enabled on Nextcloud 11 version too?

**Comment by jlord87** [comment]
@eidota have you found a solution?
I'm facing the same problem you described, except I'm on nextcloud 12...

btw, I've tried installing php-mcrypt with no results.....
