### ISSUE TITLE
Deletion of 1 SAML provider desactivate user_saml on NC 22.2.0

### ISSUE THREAD

**Issue by aagarop** [nextcloud/user_saml#555]
### Steps to reproduce
1. Create 1 SAML provider
2. Create an other SAML provider
3. Remove the first one
 
### Expected behaviour
Correctly remove the first one and keep the 2nd active 

### Actual behaviour
Totally desactivate SAML providers and redirect to /login?direct=1

### Server configuration

**Operating system**:

Debian 11

**Web server:**

Nginx

**Database:**

MySQL 

**PHP version:**

Php8.0

**Nextcloud version:** (see Nextcloud admin page)

22.2.0

**Where did you install Nextcloud from:**

Source

**List of activated apps:**

`Enabled:
  - accessibility: 1.8.0
  - bruteforcesettings: 2.2.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - encryption: 2.10.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_antivirus: 3.2.2
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_saml: 4.1.1
  - user_status: 1.2.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0`

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.0.2",
        "default_phone_region": "FR",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}

### Client configuration
**Browser:**

Firefox 93.0

**Operating system:**

Ubuntu

**Comment by Ksdmg** [comment]
I have the same issue on a fresh nextcloud instance.

**Comment by blizzz** [comment]
I was not able to reproduce the issue so far

**Comment by barrydegraaff** [comment]
I have seen this yesterday on Nextcloud 22.2.3 behavior is totally irrational when I click the Garbage bin on the second configured SAML provider, the first gets removed, but some of the settings from the second provider end up in the first provider. And when I see the login page, SAML is no longer offered.

I had to trial and error with adding and removing providers till it worked again. A similar issue is in the LDAP settings page

Also I really miss the days where one could just hit a Save button to store something other then to hope for some magic to happen and a setting to store.

**Comment by aagarop** [comment]
Not tested for a while but working now
