### ISSUE TITLE
Release notes for new versions

### ISSUE THREAD

**Issue by kosli** [nextcloud/user_saml#56]
I have seen that there are two new releass of the plugin, v10.0.2 and v9.0.55. Is there are a changelog or release notes so that i know what is new? e.g. if now multiple IDPs or a WAYF are supported? Thanks.

**Comment by LukasReschke** [comment]
The functionality is identical for 10.0.2 and 9.0.55 on the SAML app. We've updated the used SAML library which addresses some security issues though. We'll create detailed advisories about them later.
