### ISSUE TITLE
Disable Basic AUTH with user_saml

### ISSUE THREAD

**Issue by CryyDevil** [nextcloud/user_saml#569]
Hello! I have my Nextcloud with Kerberos auth, but if user has no rights, i get basic auth window .

![image](https://user-images.githubusercontent.com/96242240/146374384-08c667da-6b21-4ecb-8365-e3f530e24e79.png)

How i can disable basic auth, or redirect to page login?direct=1 ?

**Comment by blizzz** [comment]
We don't trigger basic auth, you should be redirected to either login or an error page. Seems to me like web server conf thing.
