### ISSUE TITLE
UI Interface misses elements

### ISSUE THREAD

**Issue by ReimarBauer** [nextcloud/user_saml#589]
perhaps I face an incompatibility in version 23.03.2? 

![incomplete_configs](https://user-images.githubusercontent.com/278728/159709943-2c4a1882-8aad-4984-8ef0-b5cd143c9cb4.png)

Any ideas how I could fix that?

**Comment by solracsf** [comment]
Please note app is not fully compatible with NC23: https://github.com/nextcloud/user_saml/issues/562

**Comment by blizzz** [comment]
Looks good to me for env mode.

**Comment by ReimarBauer** [comment]
I'had seen that I've used the other mode. On a NC22 I recognized that I choosed the env mode.
