### ISSUE TITLE
Environment With mod_auth_cas Doesn't Log In

### ISSUE THREAD

**Issue by necouchman** [nextcloud/user_saml#59]
I'm attempting to use user_saml with NextCloud and the mod_auth_cas Apache module.  I have mod_auth_cas working with several other applications, but when I try with NextCloud and user_saml, I get the following behavior:
- Go to NextCloud URL
- Get redirected to CAS login screen
- Log in
- Get redirected to NextCloud login screen

So, instead of actually logging in, it's just redirecting back to the NextCloud login screen.  I've followed the instructions in the manual, similar to the Kerberos example, so I'm not sure why it isn't logging in.  I'm also using LDAP authentication against active directory, and the AD logins work fine - just not the SSO.

**Comment by necouchman** [comment]
Sorry, this seems like more of a usage question and not so much an issue.  Closing it out.

**Comment by mehrdaad** [comment]
@necouchman hey, solved this issue?
