### ISSUE TITLE
`remember_login` cookie is not created

### ISSUE THREAD

**Issue by Ornanovitch** [nextcloud/user_saml#609]
### Steps to reproduce
1. keep the Nextcloud user backend activated alongside with the SAML one
2. Log in with SAML and close your tab
3. Wait around two hours
4. Go to Nextcloud

### Expected behaviour
I should be already logged in and should not have to select the backend neither to send an IdP request

### Actual behaviour
I need to select the user backend and to log in again

Keeping the Nextcloud user backend activated is necessary to see the behavior because with SAML only I guess that an IdP request is sent automatically, and therefor the "remember me" behavior seems to work although it doesn't.

FYI, user_odic creates a Remember me token : 
- https://github.com/nextcloud/user_oidc/pull/425

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "brume.felinn.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.4.1",
        "overwrite.cli.url": "https:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "default_language": "fr",
        "default_locale": "fr_FR",
        "default_phone_region": "FR",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "skeletondirectory": "\/etc\/nextcloud\/skeleton",
        "maintenance": false,
        "theme": "",
        "loglevel": 3,
        "updater.release.channel": "stable"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - apporder: 0.15.0
  - audioplayer: 3.3.0
  - bookmarks: 10.3.1
  - calendar: 3.2.2
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - dav: 1.21.0
  - event_update_notification: 1.5.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - groupfolders: 11.1.2
  - integration_gitlab: 1.0.3
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - richdocuments: 5.0.3
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - side_menu: 2.3.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_saml: 5.0.0
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - announcementcenter: 6.1.1
  - breezedark: 23.2.1
  - bruteforcesettings: 2.4.0
  - circles: 0.21.4
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - deck: 1.6.1
  - encryption
  - end_to_end_encryption: 1.9.1
  - federation: 1.10.1
  - files_external
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.9.0
  - recommendations: 0.8.0
  - spreed: 13.0.5
  - systemtags: 1.10.0
  - user_ldap
  - user_status: 1.0.0
  - weather_status: 1.0.0
```

**Comment by Ornanovitch** [comment]
@juliushaertl as you are the author of https://github.com/nextcloud/user_oidc/pull/425 on the OIDC side, have you any idea about how I could make some tests (or where to find clues) in order to consolidate my assumptions about the behavior I describe?

**Comment by juliushaertl** [comment]
The saml app works a bit differently in terms of the login of the user into the system.

It basically stores the saml data in the session 
https://github.com/nextcloud/user_saml/blob/master/lib/Controller/SAMLController.php#L350

And then validates that when checking if the user is actually logged in 
https://github.com/nextcloud/user_saml/blob/e9e55a1da1ff1e6bf829e1780a507306a97c430c/lib/UserBackend.php#L489

However it might be worth a try to see if creating a remember me token is already enough:

```
diff --git a/lib/Controller/SAMLController.php b/lib/Controller/SAMLController.php
index 476b8185..c83060ce 100644
--- a/lib/Controller/SAMLController.php
+++ b/lib/Controller/SAMLController.php
@@ -363,6 +363,8 @@ class SAMLController extends Controller {
                        return $response;
                }

+               $this->userSession->createRememberMeToken($user);
+
                $originalUrl = $data['RelayState'] ?? $data['OriginalUrl'];
                if ($originalUrl !== null && $originalUrl !== '') {
                        $response = new Http\RedirectResponse($originalUrl);
```

**Comment by Ornanovitch** [comment]
Thank you very much, I'll give it a try ASAP

**Comment by Ornanovitch** [comment]
OK done :)
Is the RememberMe cookie supposed to be created locally with something like `nc_session_id`, `nc_token` and `nc_username` ? This is what I got on another regular install without SAML, but I don't have these onto the other one (where I applied your patch) - 

I'll see in a couple of hours if it works anyway

**Comment by juliushaertl** [comment]
Keeping this open makes sense 👍

**Comment by blizzz** [comment]
@Ornanovitch you may try https://github.com/nextcloud/server/pull/32592 (without any changes to the SAML backend).

**Comment by Ornanovitch** [comment]
Awesome, I give it a try ASAP and let you know!
