### ISSUE TITLE
SP ACS (login) URL:   is  http instead of https

### ISSUE THREAD

**Issue by do-d1** [nextcloud/user_saml#620]
Hi 

nc 24.0.1 running on docker (https\ssl configured)
app - SSO & SAML authentication	5.0.1

trying to configure SAML - got errors 
checked my idp logs and there i see:

SAML request from SP 'nc.domain.com' failed: SAML assertion request validation error: ACS URL 'http://nc.domain.com/apps/user_saml/saml/acs' does not match SP setting

i change SP setting on idp to http for testing and the authentication is working - but with a warning about unsecure connection

**Comment by blizzz** [comment]
sounds to me as if your nextcloud is behind a proxy, but not configured properly.
