### ISSUE TITLE
error 500: Not valid metadata because wrong url

### ISSUE THREAD

**Issue by Mte90** [nextcloud/user_saml#654]
### Steps to reproduce
1. Just have a single IdP
2. Insert the urls and so on, check the bottom page
3. You will get a yellow badge not valid metadata but the request go on 500 and fails

![immagine](https://user-images.githubusercontent.com/403283/188845297-e22defb0-6fc6-4a70-81d3-12ec69545665.png)

If I take the url `https://domain/apps/user_saml/saml/metadata?idp=` there is a 500 but if I add 1 to the last parameter is working (download the metadata successfully).

App version 5.0.3 and nextcloud 24.0.3. I think that is just a javascript issue...
Infact https://github.com/nextcloud/user_saml/blob/34f90ee474862351b75f359b23ac1ec336cc42a5/js/admin.js#L133

![immagine](https://user-images.githubusercontent.com/403283/188846096-ec18f8fd-524b-498e-8dc3-e1dbc44006a7.png)

Infact on https://github.com/nextcloud/user_saml/blob/34f90ee474862351b75f359b23ac1ec336cc42a5/js/admin.js#L64

**Comment by blizzz** [comment]
That's fixed with #656
