### ISSUE TITLE
Internal Server Error after session_lifetime expired

### ISSUE THREAD

**Issue by mahibi** [nextcloud/user_saml#682]
### Steps to reproduce
Nextcloud v24.0.7
SAML app v5.0.3

1. User authenticates using SAML.
2. User then close the tab or browse to another site (leave Nextcloud web page).
3. Nextcloud session_lifetime expires.
4. User logout from IDP and get the error:
"Internal Server Error
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log."

**Comment by PVince81** [comment]
likely fixed by https://github.com/nextcloud/user_saml/pull/683
