### ISSUE TITLE
Login with Microsoft Azure AD and Nextcloud 25.0.6 and SSO & SAML authentication 5.1.2 fails concistently

### ISSUE THREAD

**Issue by jakobmolandergeus** [nextcloud/user_saml#715]
After upgrading from Nextcloud 25.0.5 to 25.0.6 the SSO SAML integration with Microsoft Azure AD has stopped working for us. The users can no longer login with SSO & SAML - direct login not affected.

See the : [error.log](https://github.com/nextcloud/user_saml/files/11296020/error.log)

Is this a problem with the SSO & SAML authentication app, Nextcloud or the Microsoft Azure AD configuration?

It was working before the upgrade.

Thank you in advance.

**Comment by BobSilent** [comment]
Same for me, it seems to be connected to #709 

workaround is to disable the password policy (which worked for me as well)

commandline or use direct login and disable the app.
```
php occ app:disable password_policy
```

There seems to be a fix for NC26, but I am also on NC25 and there it seems to be not available (yet)

**Comment by solracsf** [comment]
Fixed by https://github.com/nextcloud/password_policy/pull/461 (v25.0.7)
