### ISSUE TITLE
Authenticating Reverse Proxy (Caddy, Authp, Google OIDC) and Android / iOS App

### ISSUE THREAD

**Issue by pettijohn** [nextcloud/user_saml#738]
I'm not sure if this is a bug report or a feature request. 

I have Nextcloud 27 running in Docker in Apache mode. In front of it, I'm using Caddy as a reverse proxy and for SSL termination. In Caddy, I have [Authp](https://authp.github.io/) configured to [require Google authentication](https://authp.github.io/docs/authenticate/oauth/backend-oauth2-0002-google). If you attempt to access any URL behind Caddy, it will look for the JWT from Google; if you don't have it, it will redirect you to Google for you to sign in and return the token. 

Authp then transforms some of the claims from the JWT into [headers](https://authp.github.io/docs/authorize/headers#custom-headers) that it passes downstream to Nextcloud; Apache converts those headers into environment variables. 

With that, I then configured this module to run in environment variable mode, using HTTP_X_TOKEN_USER_EMAIL as UID and Email, and HTTP_X_TOKEN_USER_NAME as Display Name. 

It works great - a nextcloud admin provisions a user with the email address, and then that user can use Nextcloud from their web browser seamlessly. 

The problem/feature request I have is that I can't use the Android or iOS apps. When I input my nextcloud URL, it gives me a misconfiguration error. 

What's happening is that the app attempts to validate the URL by pinging 

```
GET status.php 
HEAD /remote.php/dav 
GET /ocs/v2.php/cloud/capabilities?format=json 
GET /index.php/login/flow
```

But those fail - Caddy sees a request without the JWT and returns a 401 and then a 302 to Google for authentication. 

Searching this repository and its issues, I don't see an answer for this. #48 says to use an app password - but that won't work in this case, since there's no way to get past the 401 without bringing a JWT from Google - Caddy/Authp handles that. 

My first thought is that the app would need to follow the OIDC flow to authenticate before it does whatever server URL validation. Maybe I should file this issue with the app? Or maybe there's some configuration option for Nextcloud I don't know about to enable that auth flow? Or I need to allow anonymous access to certain URLs in order to kick off the OIDC auth flow?

### Steps to reproduce
1. Configure Caddy to use Authp with Google ([example conf](https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/google/Caddyfile))
2. Configure user_saml in Environment mode with HTTP_X_TOKEN_USER_EMAIL as UID.
3. Sign in on desktop web browser, verify account works
4. Attempt to add this Nextcloud instance to the Android app

### Expected behaviour

App should follow the OIDC authentication flow that the reverse proxy guides them through. 

### Actual behaviour

App reports "malformed server configuration" with no further details. No logs in Nextcloud because Caddy intercepts & rejects them (401). 

### Server configuration

**Operating system**: Ubuntu 22.04

**Web server:** Apache from Docker 

**Database:** Sqlite

**PHP version:** From Docker

**Nextcloud version:** Docker, nextcloud:27

**Where did you install Nextcloud from:** Docker

**List of activated apps:** Only this

### Client configuration
**Operating system:** Current apps from both iOS and Google Play app stores. 

#### Nextcloud log (data/owncloud.log)
None - requests are intercepted by proxy and rejected 

#### Browser log
None - Android app does not show what it's doing

**Comment by blizzz** [comment]
The clients do not use SAML, but authenticate directly with an apptoken. They typically receive this after an authentication via saml through a browser view (so call login flow).

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
