### ISSUE TITLE
Invalid metadata and Internal Server Error on Nextcloud 27.0.0 and PHP 8.1.2

### ISSUE THREAD

**Issue by danfratamico** [nextcloud/user_saml#743]
On Nextcloud 27.0.0 and PHP 8.1.2, when I try to connect my instance to Azure AD and click "Download metadata", I am redirected to an Internal Server Error with URL "https://drive.domain.com/apps/user_saml/saml/metadata". In Nextcloud logs, I see the following:

> Error | PHP | foreach() argument must be of type array\|object, null given at /var/www/html/nextcloud/apps/user_saml/lib/SAMLSettings.php#119 |   | 2023-07-11T18:58:15-0400
> 
> Debug | user_saml | /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead. |   | 2023-07-11T18:58:15-0400

**Comment by solracsf** [comment]
Upgrde to 5.1.2 and report back. If error, the full stack error in JSON format from the logs.

**Comment by danfratamico** [comment]
Same error. How can I grab the full error in JSON format?

**Comment by solracsf** [comment]
In the `/data/nextcloud.log` file.
