### ISSUE TITLE
[RFE] More LDAP User Profile Attributes

### ISSUE THREAD

**Issue by slapcat** [nextcloud/user_saml#766]
It would be fantastic if you could integrate more LDAP user profile attributes, such as birthday or timezone. This would make it easier to fully integrate LDAP user management with Nextcloud Contacts.

**Comment by blizzz** [comment]
That's probably better scoped in the LDAP backend (within the server repository). SAML and LDAP backend can work together, and this is quite specifically an LDAP topic.

**Comment by slapcat** [comment]
Oops, you're right. I'll close and create it under nextcloud/server.
