### ISSUE TITLE
v5.2.3 incompatibility with guests 2.5.0 at user creation

### ISSUE THREAD

**Issue by Superjamp** [nextcloud/user_saml#777]
We are using the guests App that uses Symfony\Component\EventDispatcher\GenericEvent instead of OCP\EventDispatcher\GenericEvent

server: v26.0.8
user_saml: v5.2.3
guests: v2.5.0

result at account creation issued by ::firstLogin in UserBackend.php
```
OCA\\Guests\\Hooks::handleFirstLogin(): Argument #1 ($event) must be of type Symfony\\Component\\EventDispatcher\\GenericEvent
```
https://github.com/nextcloud/user_saml/blob/2c24631a4e66ef87f0c9edf749165f237e7023b2/lib/UserBackend.php#L171
https://github.com/nextcloud/guests/blob/6d9a2f093e2d291c8865bbe83c04c11cd462630d/lib/Hooks.php#L44

future question --> in guests master it uses OCP\User\Events\UserFirstTimeLoggedInEvent

**Comment by blizzz** [comment]
> future question --> in guests master it uses OCP\User\Events\UserFirstTimeLoggedInEvent

That's new in upcoming 28, cf https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html#added-events

**Comment by blizzz** [comment]
Fix in https://github.com/nextcloud/user_saml/pull/778
