### ISSUE TITLE
SAML users can't see any files or folders after NC-upgrade to v28.0.2

### ISSUE THREAD

**Issue by thebootable** [nextcloud/user_saml#810]
### Steps to reproduce
1. Have SAML Plugin installed
2. Update nextcloud from v27.1.6 to v28.0.2
3. Update SAML plugin
4. Login as SAML user

### Expected behaviour
Everything should be as before. The user should have the same permissions and see the same files

### Actual behaviour
SAML Users can't see any files. They can access them directly, e.g. via the "Recent" Tab, but they cant see them in "all files". All folders seem to be emtpy. A database-refresh does not make a difference. All files are still there, they just can't be seen.
New Users can be added, the default files are added but SAML users can't see them. "Regular" (Non-SAML) users can see and access their files as expected.
Mapping to the admin-group is broken. Now there are two admin-groups in nextcloud, only one being the "real" admin group with administrative privileges.
Also SAML-Users can't see group folders, although they are mapped to the correct groups. They can access them, but no files are displayed. I believe this to be just a side-effect from not seeing anything in general.

Any help is highly appreciated, thank you very much in advance! :)

### Server configuration

**Operating system**: Ubuntu 22.04.3 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 8

**Nextcloud version:** v28.0.2

**Where did you install Nextcloud from:** preinstalled package by Hetzner

**List of activated apps:**

Enabled:
  - activity: 2.20.0
  - announcementcenter: 6.7.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - collectives: 2.9.2
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - forms: 4.1.0
  - groupfolders: 16.0.3
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 6.0.1
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_saml: 6.1.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0

Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - dashboard: 7.8.0 (installed 7.5.0)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - impersonate: 1.15.0 (installed 1.15.0)
  - recommendations: 2.0.0 (installed 1.4.0)
  - related_resources: 1.3.0 (installed 1.0.3)
  - support: 1.11.0 (installed 1.8.0)
  - survey_client: 1.16.0 (installed 1.13.0)
  - suspicious_login: 6.0.0
  - twofactor_webauthn: 1.3.2 (installed 1.3.2)
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.5.0)
  - weather_status: 1.8.0 (installed 1.5.0)

**Nextcloud configuration:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "91.107.210.202",
            "cloud.juki-schoemberg.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "https:\/\/cloud.juki-schoemberg.de\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 1,
        "default_phone_region": "DE",
        "app_install_overwrite": [
            "groupfolders",
            "twofactor_reminder"
        ],
        "twofactor_enforced": {
            "false": ""
        }
    }
}

```

### Client configuration
**Browser:** Google Chrome, though Firefox has the same issue

**Operating system:** Windows 10

#### Nextcloud log (from the log interface in nextcloud)
nothing unusual, except for this exception:
```
Exception OCA\User_SAML\Controller\SAMLController::selectUserBackEnd(): Argument #1 ($redirectUrl) must be of type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 230 in file '/var/www/html/apps/user_saml/lib/Controller/SAMLController.php' line 581
```

#### Browser log
```
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.1
logger-a53a57b5.mjs:6 [INFO] activity: Activity API registered Object

circles.files.list.js?v=80e00d52-25:42 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at circles.files.list.js?v=80e00d52-25:42:55
    at circles.files.list.js?v=80e00d52-25:306:3

ConsoleLogger.js:71 [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config Objectapp: "viewer"ignoredMimes: Array(4)0: "image/heic"1: "image/heif"2: "image/tiff"3: "image/emf"length: 4[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()findLast: ƒ findLast()findLastIndex: ƒ findLastIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ (t)reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toReversed: ƒ toReversed()toSorted: ƒ toSorted()toSpliced: ƒ toSpliced()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()with: ƒ with()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {at: true, copyWithin: true, entries: true, fill: true, find: true, …}[[Prototype]]: Objectlevel: 1uid: "7"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
value @ ConsoleLogger.js:71

ConsoleLogger.js:68 [INFO] viewer: 5 viewer handlers registered Object
session-heartbeat.js:103 session heartbeat polling started

ConsoleLogger.js:68 [INFO] comments: Comments plugin registered for Activity sidebar action Object

analyser.js:485 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.
observe @ analyser.js:485

ConsoleLogger.js:74 [ERROR] files: Error while fetching content Object
value @ ConsoleLogger.js:74

NotificationsApp.vue:470 Notifications permissions not yet requested

ConsoleLogger.js:74 [ERROR] files: Header workspace already registered Object
value @ ConsoleLogger.js:74

ConsoleLogger.js:74 [ERROR] files: Error while fetching content Object
value @ ConsoleLogger.js:74

ConsoleLogger.js:74 [ERROR] files: Error while fetching content Object
value @ ConsoleLogger.js:74

lockdown-install.js:1 null
(anonymous) @ lockdown-install.js:1

lockdown-install.js:1 null
(anonymous) @ lockdown-install.js:1

```

**Comment by blizzz** [comment]
>  Mapping to the admin-group is broken. Now there are two admin-groups in nextcloud, only one being the "real" admin group with administrative privileges.

Did you have an `admin` group provided by SAML? That is an effect of the own Group Backend added in v6.1. From then on, user_saml does not manipulate foreign groups anymore. That's where the second group comes from – managed by the backend itself. 

>  Also SAML-Users can't see group folders, although they are mapped to the correct groups. They can access them, but no files are displayed. I believe this to be just a side-effect from not seeing anything in general.

Mh, double check the group folder settings. Groups that contain SAML users only are migrated automatically, that should be all transparent. If a local group contains users from mixed backends, it will be left alone, but as before an additional SAML-owned group is created, when such membership is advertised by the IdP upon login.

Generally they should see all their owned files though.

**Comment by GaugeTheory** [comment]
I am having an issue exactly for this change. I updated SAML plugin to v6.1 (It seems it can't be reverted back anymore). Now we have two admin groups. I think one id local admin groups with super admin users, and the other one SAML_admin with the users from SAML. This broke admin group assignments. 
Is there no way to make a SAML user super admin anymore with the new Group Backend?

**Comment by blizzz** [comment]
On the hand it could be considered acceptable for a group called "admin" to not create an own one. But removal would not work. Instead of having exceptions, it's better to implement IIsAdmin interface, so that the SAML backend can say itself who is admin and who not. Would need yet another setting field to declare the admin group(s).

**Comment by blizzz** [comment]
Please see https://github.com/nextcloud/server/issues/43269 for the original issues.

I opened a new ticket for the admin group thing.
