### ISSUE TITLE
Nextcloud SSO SAML environnement variable

### ISSUE THREAD

**Issue by Azgar1998** [nextcloud/user_saml#812]
I have a nextcloud (28.0.2) server linked to an LDAP directory. I configured Apache2 like this:
```
<VirtualHost *:443>
...
<Directory "/path/to/file">
...
AuthType GSSAPI
AuthName "Intranet of Geco"
GssapiCredStore keytab:/etc/key.keytab
GssapiAllowedMech krb5
Require valid-user
GssapiAllowedMech krb5
...
</Directory>
</VirtualHost>
```

The nextcloud logs come back to me:
Error while trying to login using sso environment variable: Auto provisioning not allowed and user SAMACOUNTNAME@DOMAIN does not exist

I use the "REMOTE_USER" variable for SSO. When I connect manually by doing SAMACOUNTNAME@DOMAIN it does not work.

if I log in with SAMACOUNTNAME it works.

it will certainly be necessary to delete "@DOMAIN" in the REMOTE_LOGIN variable or authorize "SAMACOUNTNAME@DOMAIN"

Do you know how to do it? what do you recommend?

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Operating system**: Ubuntu 22.04 LTS

**Web server:** Apache2

**Database:** MaraiBD

**PHP version:** 8.1.2

**Nextcloud version:** 28.0.2

**List of activated apps:**

```
Enabled:
  - activity: 2.20.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_saml: 6.1.1
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
```

**Comment by Azgar1998** [comment]
Hello,
I found regarding the authentication "SAMACCOUNTNAME@DOMAIN. it was the value "KrbLocalUserMapping On" in Apache2. but the problem is still the same i.e. I have the message "Error while trying to connect using the sso environment variable: Automatic provisioning is not allowed and user SAMACCOUNTNAME does not exist". As a reminder, login works by logging in manually with SAMACCOUNTNAME

new configuration apache2:

<Virtualhost *:443>
...
<Directory "/var/www/nextcloud/htdocs">

Do you have an idea?

...
AuthType Kerberos
AuthName "KERBEROS AUTHENTICATION"
KrbAuthRealms DOMAIN
Krb5Keytab /etc/key.keytab
KrbMethodNegotiate On
KrbSaveCredentials On
KrbVerifyKDC On
KrbServiceName Any
KrbMethodK5Passwd On
KrbLocalUserMapping On
Require valid-user
</Directory>
</Virtualhost>

**Comment by blizzz** [comment]
Hi @Azgar1998  and thanks for reaching out. This rather looks like a configuration issue, and not a case for the bug tracker. Please consider raising your concern at the [home-user forum](https://help.nextcloud.com/) or explore the [official support channels](https://nextcloud.com/contact).
