### ISSUE TITLE
Allow HTTP-POST for single logout service

### ISSUE THREAD

**Issue by jaebischer** [nextcloud/user_saml#82]
My SAML IDP (Big-IP F5 APM) does only support HTTP-POST for single logout service. However Nextcloud does not accept POST requests to URL **/saml/sls**. Is it possible to support HTTP-POST requests for SAML single logout service?

**Comment by LukasReschke** [comment]
That certainly makes sense and I'd be happy to review and accept a Pull Request on this. As the features that I'm working here for the SAML app is mainly influenced by [customer demand from Nextcloud GmbH customers](https://nextcloud.com/enterprise/) this is however not a priority for now.

So I won't have time to work on this on my own.

**Comment by smidt** [comment]
Seems like the same issue here

**Comment by fri-sch** [comment]
I have a fix (or maybe better call it a hack) for this issue: https://github.com/fri-sch/user_saml/commit/c8f6021057a558ef508c211eafc83b24833f437b

It's based on #334 and as soon as it is merged, I will send a PR for this.
