### ISSUE TITLE
invalid_response error after update to Nextcloud 11.0.1 

### ISSUE THREAD

**Issue by apweiler** [nextcloud/user_saml#83]
Hi,
we are testing Nextcloud with authentication to SAML IdP. But since updating to Nextcloud 11.0.1 it shows invalid_response errors after user get redirect from IdP. With Nextcloud 10.x and 11.0.0 it works fine. The error still occurs after updating user_saml to latest commit.

In IdP log everthing is fine. Nextcloud log has no entries about the error. Last messages in Nextcloud log are about previous cron run (some minutes ago). We are running debug loglevel.

The displayed error message is:
invalid_response

Not authenticated

**Comment by LukasReschke** [comment]
Please post your configuration. Also please add a 'debug' => true, below https://github.com/nextcloud/user_saml/blob/c96b0c15a9bd46c82ffb5ba5fe45497735a18098/lib/samlsettings.php#L46 and can you post the message then?

**Comment by apweiler** [comment]
I guess you want the user_saml config. Extracted from database (without key):
user_saml|installed_version|1.2.2
user_saml|types|authentication
user_saml|enabled|yes
user_saml|general-uid_mapping|unity:persistent
user_saml|sp-x509cert|-----BEGIN CERTIFICATE-----
MIIF6jCCBNKgAwIBAgIHG9Td43i6XDANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UE
BhMCREUxJzAlBgNVBAoTHkZvcnNjaHVuZ3N6ZW50cnVtIEp1ZWxpY2ggR21iSDEq
MCgGA1UEAxMhRlpKIENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzAyMR8wHQYJ
KoZIhvcNAQkBFhBjYUBmei1qdWVsaWNoLmRlMB4XDTE2MDgxODA3MTQyOFoXDTE5
MDcwOTIzNTkwMFowgZ0xCzAJBgNVBAYTAkRFMRwwGgYDVQQIDBNOb3JkcmhlaW4t
V2VzdGZhbGVuMRAwDgYDVQQHDAdKdWVsaWNoMScwJQYDVQQKDB5Gb3JzY2h1bmdz
emVudHJ1bSBKdWVsaWNoIEdtYkgxDDAKBgNVBAsMA0pTQzEnMCUGA1UEAwweZnNk
LWNsb3VkNjAuemFtLmtmYS1qdWVsaWNoLmRlMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEArqJLnTMEhXHQVtcG91dDjMtI2YcTFhVwF85iDqY90uqQ7qjW
AAAAfr4bt5d8jDEoaBZlSwkORKLMazuyuqaloDVWG3wU2XCUOpl4sp5uP6G6jR7q
Ay+GOGwiaNUT8/KJnlKZi74jUVt/PPD6Pk4TAzzolK9JsXsnyJD+ivfurEMi8dLz
b4G8Ba/Fv+YR5M+58wDb0zcut5sPQOYSaqbhU0cj6YTphzSwIh6JYQd56Q6fZN7V
c6lSDPRjvUE1q7dJ8skELG41lXzfTyl3R1SsT7PCXCfkUXwwj0u4tzr3H020Zn+2
+H9h0S9HKMdXbTJUv3eJHeAO5RgosxRMbURCqQIDAQABo4ICRTCCAkEwWQYDVR0g
BFIwUDARBg8rBgEEAYGtIYIsAQEEAwUwEQYPKwYBBAGBrSGCLAIBBAMBMA8GDSsG
AQQBga0hgiwBAQQwDQYLKwYBBAGBrSGCLB4wCAYGZ4EMAQICMAkGA1UdEwQCMAAw
DgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB0GA1UdDgQWBBQi
uJ8gnx3RoADywqEM4ctdSNuAxjAfBgNVHSMEGDAWgBQgvXGJpckqMy8R4B/llCZW
DxECJTApBgNVHREEIjAggh5mc2QtY2xvdWQ2MC56YW0ua2ZhLWp1ZWxpY2guZGUw
ewYDVR0fBHQwcjA3oDWgM4YxaHR0cDovL2NkcDEucGNhLmRmbi5kZS9memotY2Ev
cHViL2NybC9nX2NhY3JsLmNybDA3oDWgM4YxaHR0cDovL2NkcDIucGNhLmRmbi5k
ZS9memotY2EvcHViL2NybC9nX2NhY3JsLmNybDCBywYIKwYBBQUHAQEEgb4wgbsw
MwYIKwYBBQUHMAGGJ2h0dHA6Ly9vY3NwLnBjYS5kZm4uZGUvT0NTUC1TZXJ2ZXIv
T0NTUDBBBggrBgEFBQcwAoY1aHR0cDovL2NkcDEucGNhLmRmbi5kZS9memotY2Ev
cHViL2NhY2VydC9nX2NhY2VydC5jcnQwQQYIKwYBBQUHMAKGNWh0dHA6Ly9jZHAy
LnBjYS5kZm4uZGUvZnpqLWNhL3B1Yi9jYWNlcnQvZ19jYWNlcnQuY3J0MA0GCSqG
SIb3DQEBCwUAA4IBAQBCKwACZrIlNhMGH13ltlar8Yn+VzBhouMt14KfMs4UhWOR
G40rqh7GPjszgNZhLaGUtDcWwVeqiJpDaShHF3VxTWj5JLoQ/Q99CLKRo1zuAh8C
tJ0Z6ctWFu/7gY9+BvuRmYEkAqkTJIxJaMtJG4Xq/xDHq6ee7MP+P7cGmfMRNKj6
9FJTGnkKrt0JnBtakBQZbVG1BWMC2EsuEtVuZxhoaBQ6AN/IPhfS+nW/J16tNduR
+6IWFF1K25Bb6l42KRlcXiFYhzYIIkq1sfGcbJc7HOE03PRE1A2sQTKMprD5iK5X
osQNOQ19DCrT5Dbpc/CY/dd+wHJ5PkxNE3idtthn
-----END CERTIFICATE-----
user_saml|sp-privateKey|...
user_saml|idp-entityId|https://fsd-cloud10.zam.kfa-juelich.de
user_saml|idp-singleLogoutService.url|https://fsd-cloud10.zam.kfa-juelich.de:7000/saml-idp/SLO-WEB
user_saml|idp-singleSignOnService.url|https://fsd-cloud10.zam.kfa-juelich.de:7000/saml-idp/saml2idp-web
user_saml|idp-x509cert|-----BEGIN CERTIFICATE-----
MIIF6jCCBNKgAwIBAgIHG9Td4bsUeTANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UE
BhMCREUxJzAlBgNVBAoTHkZvcnNjaHVuZ3N6ZW50cnVtIEp1ZWxpY2ggR21iSDEq
MCgGA1UEAxMhRlpKIENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzAyMR8wHQYJ
KoZIhvcNAQkBFhBjYUBmei1qdWVsaWNoLmRlMB4XDTE2MDgxODA3MTQyNloXDTE5
MDcwOTIzNTkwMFowgZ0xCzAJBgNVBAYTAkRFMRwwGgYDVQQIDBNOb3JkcmhlaW4t
V2VzdGZhbGVuMRAwDgYDVQQHDAdKdWVsaWNoMScwJQYDVQQKDB5Gb3JzY2h1bmdz
emVudHJ1bSBKdWVsaWNoIEdtYkgxDDAKBgNVBAsMA0pTQzEnMCUGA1UEAwweZnNk
LWNsb3VkMTAuemFtLmtmYS1qdWVsaWNoLmRlMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAljVkIiBeUc8AQFv6bKQP0Ln9+gHRsGoPlq749AgByHgDoJIv
6lp51tGupmX+gpxa1mbEsx7zllhF4ECGzS/0tmdxfLiPunMFVGI/IGuN/XTOg66A
UBf2M//au03bfrUgqCE8mb5z8DQX6pEMwoELTzATXARqXJ0BcCWVhsdCJysGlC0L
gWWeE6gAd2ZMKs2OUfWbAlcoZ11mTYK7yght0IQqLp9am1SrHlTbnkssUgsFUQiO
A0Yh5U5Mndgl/hI4iXVdd3KZnJmWZ6L+aYBp/QV+Ospm15d15Ky9pyDVuxEpj/Fu
zbKkiWHzesv7gJY9fhdSIemMdKs2DrlfsNrnIwIDAQABo4ICRTCCAkEwWQYDVR0g
BFIwUDARBg8rBgEEAYGtIYIsAQEEAwUwEQYPKwYBBAGBrSGCLAIBBAMBMA8GDSsG
AQQBga0hgiwBAQQwDQYLKwYBBAGBrSGCLB4wCAYGZ4EMAQICMAkGA1UdEwQCMAAw
DgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB0GA1UdDgQWBBRB
Wt5RS6smIVA5AA/FuOjopNBNFzAfBgNVHSMEGDAWgBQgvXGJpckqMy8R4B/llCZW
DxECJTApBgNVHREEIjAggh5mc2QtY2xvdWQxMC56YW0ua2ZhLWp1ZWxpY2guZGUw
ewYDVR0fBHQwcjA3oDWgM4YxaHR0cDovL2NkcDEucGNhLmRmbi5kZS9memotY2Ev
cHViL2NybC9nX2NhY3JsLmNybDA3oDWgM4YxaHR0cDovL2NkcDIucGNhLmRmbi5k
ZS9memotY2EvcHViL2NybC9nX2NhY3JsLmNybDCBywYIKwYBBQUHAQEEgb4wgbsw
MwYIKwYBBQUHMAGGJ2h0dHA6Ly9vY3NwLnBjYS5kZm4uZGUvT0NTUC1TZXJ2ZXIv
T0NTUDBBBggrBgEFBQcwAoY1aHR0cDovL2NkcDEucGNhLmRmbi5kZS9memotY2Ev
cHViL2NhY2VydC9nX2NhY2VydC5jcnQwQQYIKwYBBQUHMAKGNWh0dHA6Ly9jZHAy
LnBjYS5kZm4uZGUvZnpqLWNhL3B1Yi9jYWNlcnQvZ19jYWNlcnQuY3J0MA0GCSqG
SIb3DQEBCwUAA4IBAQANtYfmOTAsEv010cg/qWwTIhpunYcux495Cu/qLMTsODzo
x55zbbZIfzUwlYys1KK7YUVZZDEua7h61H5ZHAOAkZoALbH6oljCBsCzqSmDVI/e
wRqusUazTVOqW2PuxmrnV5WHosEeOOBbOZggHYiOmoewcEBg0Jn64UGGLDQZN6yP
90cDzs1lypRkbKloMsohOHSiwJmLgoFaGYbWHvEZjLdZYqeb6e4K7WeWjLD96bgn
mpu1tXlkFD74M8C3TPyz/OjbQziCnJsaCxfrl5G3wLTbcmtdW2GsFKpFixE34u2q
IjV6I78GYf6fWGPpZLWznpkNts54fM8BnJUyn26n
-----END CERTIFICATE-----
user_saml|security-logoutResponseSigned|1
user_saml|security-logoutRequestSigned|1
user_saml|security-authnRequestsSigned|1
user_saml|security-nameIdEncrypted|1
user_saml|type|saml

The error message is:
Invalid issuer in the Assertion/Response
invalid_response
Not authenticated

**Comment by LukasReschke** [comment]
> Invalid issuer in the Assertion/Response

This is thrown at https://github.com/nextcloud/user_saml/blob/ea2a881e4c9fecd9b2256109a115c59a7ea7d453/3rdparty/vendor/onelogin/php-saml/lib/Saml2/Response.php#L259 whereas `idPEntityId` is the value from `idp-entityId`.

My guess is that the configured entity ID is not entirely correct. Maybe that should be "https://fsd-cloud10.zam.kfa-juelich.de:7000"? 

But in fact, yes, adding some more logging here would also help to debug such cases :-) – Until I've added some more logging for it, I'd recommend you to modify the exception https://github.com/nextcloud/user_saml/blob/ea2a881e4c9fecd9b2256109a115c59a7ea7d453/3rdparty/vendor/onelogin/php-saml/lib/Saml2/Response.php#L259 to also include `$idPEntityId` and `$trimmedIssuer`. Then that should hint more quickly what is wrong here :)

**Comment by apweiler** [comment]
Ok I was able to correct the Entity ID. Thank you very much for this fast and great support.

**Comment by LukasReschke** [comment]
> Ok I was able to correct the Entity ID. Thank you very much for this fast and great support.

Thanks for the feedback and happy to help.

I've opened a Pull Request upstream to make the error message more descriptive: https://github.com/onelogin/php-saml/pull/186
