### ISSUE TITLE
Delete no longer existing users in nextcloud

### ISSUE THREAD

**Issue by arno4000** [nextcloud/user_saml#832]
### Steps to reproduce
1. Login with a user via SSO
2. Delete the user in the SSO backend
3. Have an orphaned user in nextcloud

### Expected behaviour
There should be a way to delete users, which no longer exist in the SSO backend

### Actual behaviour
No longer existing users have to be manually cleaned up in nextcloud

### Server configuration

**Operating system**:
Debian 12 (Docker image)

**Web server:**
FPM / Nginx

**Database:**
MariaDB

**PHP version:**
The Version that comes in the Docker image

**Nextcloud version:** (see Nextcloud admin page)
All nextcloud 27 versions

**Where did you install Nextcloud from:**
Helm Chart / Docker container

**Comment by blizzz** [comment]
Nextcloud does not know which users are in your repository (unless you use it in conjunction with e.g. LDAP). The only thing the IdP does it to tell Nextcloud which user logged in, and potentially some meta data about them. The SAML protocol does not allow that by design.
