### ISSUE TITLE
SAML login on Nextcloud 28 does not work anymore

### ISSUE THREAD

**Issue by RuTHlessBEat200** [nextcloud/user_saml#865]
### Steps to reproduce
1. Install Nextcloud 28.0.7
2. Install user_saml app (6.1.3)
3. Configure SAML
4. Login wih SAML User

### Expected behaviour
The user should be logged in and see their data

### Actual behaviour
After logging in, the user does not see any data. The message “Problem loading page, reloading in X seconds” appears several times at the top right. It then starts a timer which counts down from 5 seconds and then reloads the page. As soon as this message no longer appears, the user still does not see his data. However, it can display how much storage
 the user has used at the bottom left. After pressing F5 the data is visible again. In the DevTools of the browser 
401 Unauthorized & 412 Precondition Failed appears repeatedly.
### Server configuration

**Operating system**:
Kubernetes on Linux 5.15.154-flatcar x86_64
**Web server:**
Nginx (Docker image nextcloud:28.0.7-fpm)
**Database:**
mysql 10.6.17
**PHP version:**
8.2.21
**Nextcloud version:** (see Nextcloud admin page)
nextcloud:28.0.7-fpm
**Where did you install Nextcloud from:**
https://github.com/nextcloud/helm/tree/main/charts/nextcloud

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - announcementcenter: 6.8.1
  - bruteforcesettings: 2.8.0
  - checksum: 1.2.4
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.2
  - drawio: 3.0.2
  - external: 5.3.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_antivirus: 5.5.6
  - files_automatedtagging: 1.18.0
  - files_mindmap: 0.0.30
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_retention: 1.17.2
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - metadata: 0.20.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.1
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.2
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_saml: 6.1.3
  - user_status: 1.8.1
  - user_usage_report: 1.12.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0 (installed 26.0.0)
  - dashboard: 7.8.0 (installed 7.0.0)
  - encryption: 2.16.0 (installed 2.13.0)
  - files_external: 1.20.0 (installed 1.18.0)
  - suspicious_login: 6.0.0 (installed 4.4.0)

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "default_phone_region": "ch",
        "proxy": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": ***REMOVED SENSITIVE VALUE***
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.7.4",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "dbport": "",
        "dbtableprefix": "oc_",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "log_rotate_size": "5242880000",
        "maintenance": false,
        "skeletondirectory": "",
        "ldapUserCleanupInterval": "20",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable"
    }
}

### Client configuration
**Browser:**
google-chrome 126.0.6478.182-1 
**Operating system:**
EndeavourOS
#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```
nothing useful in here
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
[devtools_output.json](https://github.com/user-attachments/files/16279650/devtools_output.json)

**Comment by arno4000** [comment]
I also have the same problem, would really appreciate a fix

**Comment by blizzz** [comment]
Not a SAML issue. Fixed on the server with https://github.com/nextcloud/server/pull/46398 and will be released with next maintenance release, expected today.
