### ISSUE TITLE
After upgrading from NC 9 to NC 11.0.1.2, SSO & SAML authentication is broken.

### ISSUE THREAD

**Issue by barinder** [nextcloud/user_saml#87]
Hello, 
After upgrading from NC9 to NC 11, the SSO authentication is not working any more, we are using LDAP and Shibboleth as backend, and it doesn't redirect to Shibboleth for authentication.  

We are using built-in SAML authentication, we are not sure if its required to change configuration in newer version. 

Can anybody help us here ?

**Comment by LukasReschke** [comment]
Likely related to https://github.com/nextcloud/user_saml/issues/83 - can you check https://github.com/nextcloud/user_saml/issues/83#issuecomment-277218447?

**Comment by barinder** [comment]
This seems to be a different issue then #83 - In our case it simply not re-directing to the Shibboleth for authentication and no error is thrown.

**Comment by LukasReschke** [comment]
As this seems like an environment related issue and our integration tests for Shibboleth still work properly I'd like to ask you to reopen this on https://help.nextcloud.com/. Thanks!
