### ISSUE TITLE
Logging in with User_SAML overwrites the displayname of users

### ISSUE THREAD

**Issue by eidota** [nextcloud/user_saml#97]
### Steps to reproduce

We have the following configuration: Once a night we pull all user data from LDAP and then create/update/delete users locally in Nextcloud with a script that does occ and web-api calls. We provide an username, displayname and email. Users log in with Shibboleth (User_SAML).

1. Have a local user structure and authentification with User_SAML up and running
2. confirm the displayname for user TEST in the database (table: oc_users) is set appropriately
3. Log-in with user TEST

### Expected behaviour
Displayname should be persistent

### Actual behaviour
After user TEST logged-in successfully the displayname is set automatically to the uid. The previous and correct displayname is lost.

### Server configuration
**Operating system**: Ubuntu 16.04.4

**Web server:** Apache 2.4.18 

**Database:** MariaDB 10.0.29

**PHP version:** 7.0.15

**Nextcloud version:** 11.0.1

**User_SAML version:**  1.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Migrated from ownCloud

**Where did you install Nextcloud from:** Your website

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_saml: 1.2.2
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

 "system": {
        "instanceid": "och2q4sieriy",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx.de",
            "xxx.de",
            "xxx.de"
        ],
        "datadirectory": "\/nfs\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxx.de",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_from_address": "nobody",
        "mail_smtpmode": "php",
        "mail_domain": "xxx.de",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "loglevel": 2,
        "ldapIgnoreNamingRules": false,
        "forcessl": true,
        "has_internet_connection": true,
        "maintenance": false,
        "ldapUserCleanupInterval": 51,
        "singleuser": false,
        "default_language": "de_DE",
        "allow_user_to_change_display_name": false,
        "trashbin_retention_obligation": "5, 14",
        "versions_retention_obligation": "auto, 30",
        "enable_previews": true,
        "tempdirectory": "\/nfs\/owncloud\/tmp",
        "theme": "tuhh",
        "log_rotate_size": "52428800",
        "knowledgebaseenabled": false,
        "skeletondirectory": "\/disk1\/webserver\/owncloud\/themes\/tuhh\/core\/skeleton\/",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis"
    }

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:**no

**Comment by eidota** [comment]
@LukasReschke could you please take a look? We want to include about 10k new users this month, but if them logging in erases the displayname we cant do that as people would be unable to share by displayname.

**Comment by LukasReschke** [comment]
Thanks for your bug report. Note that my schedule is rather tight and as an employee of [Nextcloud GmbH](https://nextcloud.com) my schedule is usually filled already with customer issues. I will take a look at this later but can't give any estimates. That said, with more than 10k users getting in touch with sales@nextcloud.com may be a sensible thing to do :)

**Comment by szabogyula** [comment]
The resolver commit is here: nextcloud/server@92c74d2 

Release: https://github.com/nextcloud/server/releases/tag/v12.0.0beta4
